# Creating Spark DF

In [0]:
# while we have worked with spark RDD whe created or read the data from SparkContext. So if we read the data from the SparkContext spark will provide the data as RDD
# If we read the data from SparkSession spark will provide the data in dataframe.

from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('Spark DataFrame').getOrCreate() # here it will create only one sparksession

df = spark.read.csv('/FileStore/tables/StudentData.csv') # this is transformation in which we are reading the data
df.show() # this is action

+---+------+----------------+------+------+-----+--------------------+
|_c0|   _c1|             _c2|   _c3|   _c4|  _c5|                 _c6|
+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
| 28|Female| Hubert Oliveras|    DB| 02984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

In [0]:
# for handling headers

df = spark.read.option('header', True).csv('/FileStore/tables/StudentData.csv')
df.show()

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB| 02984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

# Spark infer Schema (Schema of Dataframe)

In [0]:
df = spark.read.option('header', True).csv('/FileStore/tables/StudentData.csv')
df.printSchema() # it will provide the scheama of table (like dir in MySQL)

root
 |-- age: string (nullable = true)
 |-- gender: string (nullable = true)
 |-- name: string (nullable = true)
 |-- course: string (nullable = true)
 |-- roll: string (nullable = true)
 |-- marks: string (nullable = true)
 |-- email: string (nullable = true)

In [0]:
df = spark.read.option('inferSchema', True).option('header', True).csv('/FileStore/tables/StudentData.csv') # now we will get actual datatypes present in the table
df.printSchema()

root
 |-- age: integer (nullable = true)
 |-- gender: string (nullable = true)
 |-- name: string (nullable = true)
 |-- course: string (nullable = true)
 |-- roll: integer (nullable = true)
 |-- marks: integer (nullable = true)
 |-- email: string (nullable = true)

In [0]:
# using options()
df = spark.read.options(inferSchema='True', header='True', delemeter=',').csv('/FileStore/tables/StudentData.csv') # no matter in which format the data is(csv, tsv, xlst,..) spark will read the data but we need to provide appropriate delemater
df.printSchema()
df.show()

root
 |-- age: integer (nullable = true)
 |-- gender: string (nullable = true)
 |-- name: string (nullable = true)
 |-- course: string (nullable = true)
 |-- roll: integer (nullable = true)
 |-- marks: integer (nullable = true)
 |-- email: string (nullable = true)

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

# Spark Provide Schema

In [0]:
# if we want to change the datatypes of schema then..

#if we do 'inferschema' by default values will get add for(2-int, 2.3-float, 'abc'-string). If we want to explicetly changet the types follow the below staps

from pyspark.sql.types import StructType, StructField, IntegerType, StringType
from pyspark.sql import SparkSession

schemaa = StructType([
    StructField('age', IntegerType(), True),
    StructField('gender', StringType(), True),
    StructField('name', StringType(), True),
    StructField('course', StringType(), True),
    StructField('roll', StringType(), True), #check the difference here
    StructField('marks', IntegerType(), True),
    StructField('email', StringType(), True)
])

spark = SparkSession.builder.appName('Provide Schema').getOrCreate()
df = spark.read.options(header='True').schema(schemaa).csv('/FileStore/tables/StudentData.csv')
df.printSchema()

root
 |-- age: integer (nullable = true)
 |-- gender: string (nullable = true)
 |-- name: string (nullable = true)
 |-- course: string (nullable = true)
 |-- roll: string (nullable = true)
 |-- marks: integer (nullable = true)
 |-- email: string (nullable = true)

# Create DF from RDD

In [0]:
from pyspark import SparkConf, SparkContext
from pyspark.sql import SparkSession

# creating DF
spark = SparkSession.builder.appName('DF').getOrCreate()

# creating RDD
conf = SparkConf().setAppName('RDD')
sc = SparkContext.getOrCreate(conf=conf)
rdd = sc.textFile('/FileStore/tables/StudentData.csv')

# basic transformations to remove headers
header = rdd.first()
rdd1 = rdd.filter(lambda x: x != header).map(lambda x: x.split(','))
rdd1.collect()

Out[12]: [['28',
  'Female',
  'Hubert Oliveras',
  'DB',
  '02984',
  '59',
  'Annika Hoffman_Naoma Fritts@OOP.com'],
 ['29',
  'Female',
  'Toshiko Hillyard',
  'Cloud',
  '12899',
  '62',
  'Margene Moores_Marylee Capasso@DB.com'],
 ['28',
  'Male',
  'Celeste Lollis',
  'PF',
  '21267',
  '45',
  'Jeannetta Golden_Jenna Montague@DSA.com'],
 ['29',
  'Female',
  'Elenore Choy',
  'DB',
  '32877',
  '29',
  'Billi Clore_Mitzi Seldon@DB.com'],
 ['28',
  'Male',
  'Sheryll Towler',
  'DSA',
  '41487',
  '41',
  'Claude Panos_Judie Chipps@OOP.com'],
 ['28',
  'Male',
  'Margene Moores',
  'MVC',
  '52771',
  '32',
  'Toshiko Hillyard_Clementina Menke@MVC.com'],
 ['28',
  'Male',
  'Neda Briski',
  'OOP',
  '61973',
  '69',
  'Alberta Freund_Elenore Choy@DB.com'],
 ['28',
  'Female',
  'Claude Panos',
  'Cloud',
  '72409',
  '85',
  'Sheryll Towler_Alberta Freund@Cloud.com'],
 ['28',
  'Male',
  'Celeste Lollis',
  'MVC',
  '81492',
  '64',
  'Nicole Harwood_Claude Panos@MVC.com'],
 ['29',
  'Male',
  'Cordie Harnois',
  'OOP',
  '92882',
  '51',
  'Judie Chipps_Clementina Menke@MVC.com'],
 ['29',
  'Female',
  'Kena Wild',
  'DSA',
  '102285',
  '35',
  'Dustin Feagins_Margene Moores@OOP.com'],
 ['29',
  'Male',
  'Ernest Rossbach',
  'DB',
  '111449',
  '53',
  'Maybell Duguay_Abram Nagao@OOP.com'],
 ['28',
  'Female',
  'Latia Vanhoose',
  'DB',
  '122502',
  '27',
  'Latia Vanhoose_Mitzi Seldon@OOP.com'],
 ['29',
  'Female',
  'Latia Vanhoose',
  'MVC',
  '132110',
  '55',
  'Eda Neathery_Nicole Harwood@Cloud.com'],
 ['29',
  'Male',
  'Neda Briski',
  'PF',
  '141770',
  '42',
  'Margene Moores_Michelle Ruggiero@MVC.com'],
 ['29',
  'Female',
  'Latia Vanhoose',
  'DB',
  '152159',
  '27',
  'Claude Panos_Santa Kerfien@DB.com'],
 ['29',
  'Male',
  'Loris Crossett',
  'MVC',
  '161771',
  '36',
  'Mitzi Seldon_Jenna Montague@MVC.com'],
 ['29',
  'Male',
  'Annika Hoffman',
  'OOP',
  '171660',
  '22',
  'Taryn Brownlee_Mitzi Seldon@MVC.com'],
 ['29',
  'Male',
  'Santa Kerfien',
  'PF',
  '182129',
  '56',
  'Judie Chipps_Taryn Brownlee@Cloud.com'],
 ['28',
  'Female',
  'Mickey Cortright',
  'DB',
  '192537',
  '62',
  'Ernest Rossbach_Marylee Capasso@Cloud.com'],
 ['29',
  'Female',
  'Loris Crossett',
  'PF',
  '201487',
  '96',
  'Elenore Choy_Latia Vanhoose@Cloud.com'],
 ['29',
  'Female',
  'Niki Klimek',
  'PF',
  '211508',
  '23',
  'Cordie Harnois_Judie Chipps@PF.com'],
 ['28',
  'Female',
  'Kena Wild',
  'Cloud',
  '221750',
  '60',
  'Mitzi Seldon_Jenna Montague@DSA.com'],
 ['28',
  'Female',
  'Jc Andrepont',
  'DSA',
  '232060',
  '58',
  'Billi Clore_Abram Nagao@MVC.com'],
 ['29',
  'Female',
  'Anna Santos',
  'Cloud',
  '242254',
  '68',
  'Jc Andrepont_Hubert Oliveras@Cloud.com'],
 ['28',
  'Female',
  'Alberta Freund',
  'OOP',
  '251805',
  '83',
  'Annika Hoffman_Sheryll Towler@MVC.com'],
 ['28',
  'Female',
  'Maybell Duguay',
  'Cloud',
  '261439',
  '20',
  'Nicole Harwood_Judie Chipps@DB.com'],
 ['29',
  'Female',
  'Paris Hutton',
  'DSA',
  '271472',
  '99',
  'Sheryll Towler_Alberta Freund@DSA.com'],
 ['29',
  'Female',
  'Cheri Kenney',
  'Cloud',
  '281408',
  '43',
  'Annika Hoffman_Melani Engberg@Cloud.com'],
 ['28',
  'Female',
  'Dustin Feagins',
  'DSA',
  '291984',
  '82',
  'Abram Nagao_Kena Wild@Cloud.com'],
 ['29',
  'Female',
  'Claude Panos',
  'Cloud',
  '302130',
  '59',
  'Sheryll Towler_Leontine Phillips@PF.com'],
 ['28',
  'Female',
  'Anna Santos',
  'DB',
  '311589',
  '79',
  'Celeste Lollis_Mickey Cortright@DSA.com'],
 ['28',
  'Female',
  'Cheri Kenney',
  'MVC',
  '321816',
  '24',
  'Kena Wild_Michelle Ruggiero@DB.com'],
 ['28',
  'Female',
  'Loris Crossett',
  'PF',
  '332739',
  '62',
  'Michelle Ruggiero_Clementina Menke@DB.com'],
 ['28',
  'Female',
  'Mickey Cortright',
  'DSA',
  '342003',
  '44',
  'Mitzi Seldon_Jeannetta Golden@PF.com'],
 ['28',
  'Male',
  'Hubert Oliveras',
  'OOP',
  '351719',
  '63',
  'Lawanda Wohlwend_Abram Nagao@MVC.com'],
 ['28',
  'Male',
  'Sebrina Maresca',
  'PF',
  '361316',
  '62',
  'Nicole Harwood_Latia Vanhoose@DB.com'],
 ['29',
  'Male',
  'Jalisa Swenson',
  'PF',
  '372873',
  '45',
  'Ernest Rossbach_Toshiko Hillyard@DB.com'],
 ['28',
  'Male',
  'Kizzy Brenner',
  'DB',
  '381712',
  '36',
  'Paris Hutton_Kena Wild@MVC.com'],
 ['28',
  'Male',
  'Toshiko Hillyard',
  'DB',
  '392218',
  '47',
  'Leontine Phillips_Billi Clore@MVC.com'],
 ['28',
  'Female',
  'Kizzy Brenner',
  'Cloud',
  '402409',
  '27',
  'Ernest Rossbach_Gonzalo Ferebee@OOP.com'],
 ['29',
  'Female',
  'Anna Santos',
  'DSA',
  '411479',
  '42',
  'Kena Wild_Mitzi Seldon@DB.com'],
 ['28',
  'Male',
  'Elenore Choy',
  'PF',
  '422704',
  '66',
  'Marylee Capasso_Nicole Harwood@MVC.com'],
 ['28',
  'Female',
  'Jalisa Swenson',
  'OOP',
  '431352',
  '25',
  'Gonzalo Ferebee_Judie Chipps@DB.com'],
 ['29',
  'Female',
  'Somer Stoecker',
  'Cloud',
  '442028',
  '34',
  'Taryn Brownlee_Taryn Brownlee@MVC.com'],
 ['28',
  'Female',
  'Maybell Duguay',
  'DSA',
  '452141',
  '29',
  'Leontine Phillips_Elenore Choy@Cloud.com'],
 ['28',
  'Male',
  'Dustin Feagins',
  'PF',
  '461839',
  '51',
  'Neda Briski_Elenore Choy@Cloud.com'],
 ['29',
  'Male',
  'Annika Hoffman',
  'OOP',
  '472550',
  '35',
  'Mitzi Seldon_Abram Nagao@DSA.com'],
 ['29',
  'Male',
  'Paris Hutton',
  'DB',
  '481229',
  '57',
  'Clementina Menke_Paris Hutton@MVC.com'],
 ['29',
  'Female',
  'Paris Hutton',
  'DSA',
  '492159',
  '60',
  'Nicole Harwood_Marylee Capasso@OOP.com'],
 ['29',
  'Female',
  'Jenna Montague',
  'MVC',
  '502585',
  '43',
  'Hubert Oliveras_Jc Andrepont@DSA.com'],
 ['29',
  'Male',
  'Billi Clore',
  'Cloud',
  '512047',
  '76',
  'Taryn Brownlee_Judie Chipps@DSA.com'],
 ['29',
  'Male',
  'Toshiko Hillyard',
  'OOP',
  '521221',
  '77',
  'Hubert Oliveras_Latia Vanhoose@MVC.com'],
 ['28',
  'Male',
  'Margene Moores',
  'PF',
  '531530',
  '53',
  'Cheri Kenney_Melani Engberg@OOP.com'],
 ['29',
  'Female',
  'Claude Panos',
  'OOP',
  '542821',
  '28',
  'Hubert Oliveras_Priscila Tavernier@PF.com'],
 ['28',
  'Female',
  'Mickey Cortright',
  'DB',
  '551389',
  '43',
  'Tijuana Kropf_Jenna Montague@DB.com'],
 ['29',
  'Male',
  'Celeste Lollis',
  'DSA',
  '562065',
  '85',
  'Jc Andrepont_Melani Engberg@OOP.com'],
 ['28',
  'Female',
  'Tijuana Kropf',
  'PF',
  '571047',
  '41',
  'Loris Crossett_Sebrina Maresca@PF.com'],
 ['28',
  'Male',
  'Marylee Capasso',
  'OOP',
  '581756',
  '52',
  'Jeannetta Golden_Loris Crossett@MVC.com'],
 ['29',
  'Male',
  'Maybell Duguay',
  'DSA',
  '592061',
  '83',
  'Eda Neathery_Jenna Montague@Cloud.com'],
 ['28',
  'Female',
  'Leontine Phillips',
  'DB',
  '602404',
  '48',
  'Neda Briski_Cheri Kenney@PF.com'],
 ['28',
  'Female',
  'Somer Stoecker',
  'Cloud',
  '612490',
  '82',
  'Sebrina Maresca_Gonzalo Ferebee@DSA.com'],
 ['28',
  'Male',
  'Mitzi Seldon',
  'DSA',
  '622981',
  '45',
  'Lawanda Wohlwend_Loris Crossett@DSA.com'],
 ['29',
  'Female',
  'Judie Chipps',
  'Cloud',
  '632793',
  '75',
  'Tijuana Kropf_Elenore Choy@PF.com'],
 ['28',
  'Male',
  'Priscila Tavernier',
  'PF',
  '642594',
  '27',
  'Marylee Capasso_Claude Panos@DSA.com'],
 ['29',
  'Male',
  'Tamera Blakley',
  'MVC',
  '651649',
  '92',
  'Latia Vanhoose_Toshiko Hillyard@MVC.com'],
 ['28',
  'Male',
  'Sheryll Towler',
  'MVC',
  '661079',
  '89',
  'Tijuana Kropf_Mickey Cortright@DB.com'],
 ['29',
  'Male',
  'Hubert Oliveras',
  'MVC',
  '672451',
  '28',
  'Annika Hoffman_Mickey Cortright@DSA.com'],
 ['29',
  'Male',
  'Sheryll Towler',
  'PF',
  '682533',
  '42',
  'Billi Clore_Anna Santos@PF.com'],
 ['28',
  'Female',
  'Jenna Montague',
  'DSA',
  '691564',
  '26',
  'Mitzi Seldon_Sebrina Maresca@Cloud.com'],
 ['29',
  'Male',
  'Maybell Duguay',
  'PF',
  '701486',
  '99',
  'Clementina Menke_Latia Vanhoose@Cloud.com'],
 ['29',
  'Male',
  'Jenna Montague',
  'MVC',
  '711153',
  '45',
  'Marylee Capasso_Hubert Oliveras@DB.com'],
 ['28',
  'Male',
  'Annika Hoffman',
  'Cloud',
  '722193',
  '55',
  'Taryn Brownlee_Elenore Choy@DB.com'],
 ['28',
  'Female',
  'Celeste Lollis',
  'DSA',
  '731879',
  '76',
  'Hubert Oliveras_Gonzalo Ferebee@DSA.com'],
 ['29',
  'Male',
  'Jeannetta Golden',
  'MVC',
  '741875',
  '57',
  'Sheryll Towler_Cheri Kenney@DSA.com'],
 ['29',
  'Male',
  'Paris Hutton',
  'MVC',
  '752504',
  '22',
  'Elenore Choy_Elenore Choy@DB.com'],
 ['29',
  'Female',
  'Margene Moores',
  'MVC',
  '761843',
  '48',
  'Ernest Rossbach_Mickey Cortright@DSA.com'],
 ['28',
  'Female',
  'Hubert Oliveras',
  'DB',
  '771081',
  '79',
  'Kizzy Brenner_Dustin Feagins@MVC.com'],
 ['28',
  'Male',
  'Alberta Freund',
  'PF',
  '781061',
  '75',
  'Leontine Phillips_Bonita Higuera@PF.com'],
 ['29',
  'Female',
  'Billi Clore',
  'OOP',
  '791519',
  '93',
  'Elenore Choy_Jalisa Swenson@MVC.com'],
 ['28',
  'Female',
  'Billi Clore',
  'Cloud',
  '801693',
  '38',
  'Niki Klimek_Kizzy Brenner@DB.com'],
 ['29',
  'Female',
  'Elenore Choy',
  'DB',
  '811824',
  '55',
  'Maybell Duguay_Melani Engberg@DB.com'],
 ['28',
  'Male',
  'Anna Santos',
  'OOP',
  '822396',
  '47',
  'Leontine Phillips_Gonzalo Ferebee@Cloud.com'],
 ['28',
  'Male',
  'Sheryll Towler',
  'DSA',
  '831562',
  '59',
  'Kena Wild_Gonzalo Ferebee@Cloud.com'],
 ['29',
  'Male',
  'Neda Briski',
  'PF',
  '842515',
  '68',
  'Neda Briski_Hubert Oliveras@OOP.com'],
 ['28',
  'Female',
  'Santa Kerfien',
  'Cloud',
  '851620',
  '34',
  'Melani Engberg_Sheryll Towler@PF.com'],
 ['29',
  'Female',
  'Taryn Brownlee',
  'MVC',
  '861849',
  '39',
  'Billi Clore_Toshiko Hillyard@MVC.com'],
 ['28',
  'Female',
  'Sheryll Towler',
  'DSA',
  '871967',
  '64',
  'Michelle Ruggiero_Billi Clore@Cloud.com'],
 ['29',
  'Male',
  'Clementina Menke',
  'DB',
  '882200',
  '76',
  'Michelle Ruggiero_Jenna Montague@MVC.com'],
 ['28',
  'Male',
  'Margene Moores',
  'DSA',
  '892010',
  '93',
  'Anna Santos_Naoma Fritts@DSA.com'],
 ['28',
  'Female',
  'Somer Stoecker',
  'DSA',
  '901958',
  '64',
  'Kizzy Brenner_Jc Andrepont@DB.com'],
 ['29',
  'Male',
  'Loris Crossett',
  'PF',
  '911593',
  '46',
  'Gonzalo Ferebee_Mitzi Seldon@PF.com'],
 ['29',
  'Female',
  'Sebrina Maresca',
  'DB',
  '922210',
  '54',
  'Toshiko Hillyard_Santa Kerfien@MVC.com'],
 ['29',
  'Male',
  'Naoma Fritts',
  'DB',
  '931295',
  '79',
  'Hubert Oliveras_Sheryll Towler@DSA.com'],
 ['28',
  'Female',
  'Santa Kerfien',
  'MVC',
  '941783',
  '94',
  'Paris Hutton_Naoma Fritts@DB.com'],
 ['28',
  'Female',
  'Lawanda Wohlwend',
  'DSA',
  '951686',
  '60',
  'Loris Crossett_Nicole Harwood@DSA.com'],
 ['29',
  'Male',
  'Abram Nagao',
  'MVC',
  '962235',
  '32',
  'Jenna Montague_Gonzalo Ferebee@DSA.com'],
 ['28',
  'Female',
  'Jc Andrepont',
  'PF',
  '972733',
  '20',
  'Eda Neathery_Eda Neathery@MVC.com'],
 ['29',
  'Male',
  'Niki Klimek',
  'PF',
  '982443',
  '94',
  'Santa Kerfien_Kizzy Brenner@DB.com'],
 ['28',
  'Female',
  'Marylee Capasso',
  'OOP',
  '991770',
  '86',
  'Margene Moores_Clementina Menke@DB.com'],
 ['28',
  'Male',
  'Jenna Montague',
  'DSA',
  '1002103',
  '36',
  'Melani Engberg_Hubert Oliveras@PF.com'],
 ['29',
  'Female',
  'Eda Neathery',
  'Cloud',
  '1011971',
  '91',
  'Margene Moores_Elenore Choy@MVC.com'],
 ['29',
  'Male',
  'Michelle Ruggiero',
  'DSA',
  '1022971',
  '99',
  'Cordie Harnois_Clementina Menke@OOP.com'],
 ['28',
  'Male',
  'Annika Hoffman',
  'DB',
  '1031544',
  '44',
  'Dustin Feagins_Somer Stoecker@DB.com'],
 ['29',
  'Female',
  'Hubert Oliveras',
  'DSA',
  '1041483',
  '28',
  'Billi Clore_Santa Kerfien@DSA.com'],
 ['28',
  'Male',
  'Billi Clore',
  'MVC',
  '1052566',
  '78',
  'Naoma Fritts_Margene Moores@DSA.com'],
 ['28',
  'Female',
  'Nicole Harwood',
  'MVC',
  '1061068',
  '82',
  'Santa Kerfien_Hubert Oliveras@MVC.com'],
 ['29',
  'Male',
  'Clementina Menke',
  'PF',
  '1071717',
  '54',
  'Celeste Lollis_Leontine Phillips@OOP.com'],
 ['28',
  'Female',
  'Claude Panos',
  'OOP',
  '1081294',
  '94',
  'Kizzy Brenner_Anna Santos@OOP.com'],
 ['29',
  'Male',
  'Donna Yerby',
  'DSA',
  '1092702',
  '79',
  'Marylee Capasso_Alberta Freund@OOP.com'],
 ['29',
  'Female',
  'Maybell Duguay',
  'MVC',
  '1102536',
  '22',
  'Somer Stoecker_Marylee Capasso@OOP.com'],
 ['29',
  'Male',
  'Abram Nagao',
  'PF',
  '1112161',
  '42',
  'Nicole Harwood_Niki Klimek@DB.com'],
 ['28',
  'Female',
  'Bonita Higuera',
  'DSA',
  '1122348',
  '51',
  'Somer Stoecker_Jenna Montague@DB.com'],
 ['29',
  'Female',
  'Melani Engberg',
  'OOP',
  '1132093',
  '76',
  'Kena Wild_Neda Briski@Cloud.com'],
 ['29',
  'Female',
  'Marylee Capasso',
  'OOP',
  '1142653',
  '61',
  'Cordie Harnois_Alberta Freund@DSA.com'],
 ['29',
  'Male',
  'Nicole Harwood',
  'Cloud',
  '1152571',
  '62',
  'Latia Vanhoose_Maybell Duguay@PF.com'],
 ['29',
  'Female',
  'Dustin Feagins',
  'OOP',
  '1161607',
  '37',
  'Eda Neathery_Marylee Capasso@MVC.com'],
 ['28',
  'Female',
  'Niki Klimek',
  'PF',
  '1172784',
  '24',
  'Jeannetta Golden_Abram Nagao@MVC.com'],
 ['29',
  'Female',
  'Abram Nagao',
  'DSA',
  '1181007',
  '57',
  'Anna Santos_Anna Santos@DSA.com'],
 ['28',
  'Male',
  'Jalisa Swenson',
  'PF',
  '1192555',
  '77',
  'Marylee Capasso_Celeste Lollis@Cloud.com'],
 ['29',
  'Female',
  'Ernest Rossbach',
  'MVC',
  '1201427',
  '80',
  'Elenore Choy_Jenna Montague@OOP.com'],
 ['28',
  'Male',
  'Nicole Harwood',
  'DB',
  '1211495',
  '28',
  'Melani Engberg_Jc Andrepont@Cloud.com'],
 ['29',
  'Female',
  'Claude Panos',
  'DB',
  '1222887',
  '75',
  'Hubert Oliveras_Somer Stoecker@Cloud.com'],
 ['28',
  'Female',
  'Cordie Harnois',
  'OOP',
  '1231943',
  '68',
  'Mickey Cortright_Kizzy Brenner@OOP.com'],
 ['28',
  'Male',
  'Nicole Harwood',
  'OOP',
  '1242426',
  '71',
  'Billi Clore_Loris Crossett@Cloud.com'],
 ['28',
  'Male',
  'Gonzalo Ferebee',
  'Cloud',
  '1251176',
  '60',
  'Santa Kerfien_Tamera Blakley@PF.com'],
 ['29',
  'Male',
  'Jalisa Swenson',
  'Cloud',
  '1261533',
  '70',
  'Dustin Feagins_Nicole Harwood@PF.com'],
 ['28',
  'Female',
  'Eda Neathery',
  'Cloud',
  '1272870',
  '69',
  'Somer Stoecker_Dustin Feagins@DB.com'],
 ['28',
  'Female',
  'Toshiko Hillyard',
  'DSA',
  '1282835',
  '79',
  'Somer Stoecker_Toshiko Hillyard@OOP.com'],
 ['28',
  'Male',
  'Paris Hutton',
  'MVC',
  '1292279',
  '26',
  'Paris Hutton_Eda Neathery@DSA.com'],
 ['29',
  'Female',
  'Niki Klimek',
  'DB',
  '1301784',
  '24',
  'Celeste Lollis_Tamera Blakley@DB.com'],
 ['28',
  'Male',
  'Bonita Higuera',
  'Cloud',
  '1312294',
  '94',
  'Eda Neathery_Priscila Tavernier@PF.com'],
 ['28',
  'Female',
  'Leontine Phillips',
  'MVC',
  '1322629',
  '87',
  'Judie Chipps_Michelle Ruggiero@Cloud.com'],
 ['29',
  'Male',
  'Jalisa Swenson',
  'PF',
  '1332072',
  '88',
  'Billi Clore_Kizzy Brenner@Cloud.com'],
 ['28',
  'Male',
  'Clementina Menke',
  'OOP',
  '1341574',
  '46',
  'Elenore Choy_Mickey Cortright@DB.com'],
 ['28',
  'Male',
  'Gonzalo Ferebee',
  'PF',
  '1352348',
  '95',
  'Neda Briski_Somer Stoecker@DB.com'],
 ['29',
  'Female',
  'Jalisa Swenson',
  'DSA',
  '1362151',
  '51',
  'Lawanda Wohlwend_Jenna Montague@PF.com'],
 ['28',
  'Male',
  'Lawanda Wohlwend',
  'PF',
  '1372552',
  '88',
  'Hubert Oliveras_Tijuana Kropf@DSA.com'],
 ['28',
  'Male',
  'Abram Nagao',
  'DSA',
  '1382959',
  '66',
  'Michelle Ruggiero_Kena Wild@OOP.com'],
 ['29',
  'Female',
  'Hubert Oliveras',
  'Cloud',
  '1392791',
  '94',
  'Anna Santos_Alberta Freund@Cloud.com'],
 ['28',
  'Male',
  'Bonita Higuera',
  'Cloud',
  '1401526',
  '24',
  'Jc Andrepont_Cheri Kenney@Cloud.com'],
 ['29',
  'Female',
  'Clementina Menke',
  'OOP',
  '1412376',
  '65',
  'Elenore Choy_Latia Vanhoose@DSA.com'],
 ['29',
  'Female',
  'Mickey Cortright',
  'Cloud',
  '1421542',
  '71',
  'Latia Vanhoose_Kena Wild@OOP.com'],
 ['29',
  'Female',
  'Leontine Phillips',
  'DB',
  '1432252',
  '67',
  'Billi Clore_Sheryll Towler@DB.com'],
 ['28',
  'Female',
  'Nicole Harwood',
  'PF',
  '1441367',
  '95',
  'Jc Andrepont_Anna Santos@DSA.com'],
 ['28',
  'Female',
  'Gonzalo Ferebee',
  'DB',
  '1451513',
  '69',
  'Claude Panos_Tamera Blakley@PF.com'],
 ['29',
  'Female',
  'Judie Chipps',
  'DB',
  '1461078',
  '31',
  'Tijuana Kropf_Billi Clore@OOP.com'],
 ['29',
  'Male',
  'Niki Klimek',
  'MVC',
  '1472917',
  '36',
  'Sebrina Maresca_Sheryll Towler@MVC.com'],
 ['29',
  'Female',
  'Lawanda Wohlwend',
  'MVC',
  '1482889',
  '65',
  'Gonzalo Ferebee_Dustin Feagins@PF.com'],
 ['28',
  'Male',
  'Jc Andrepont',
  'DSA',
  '1492828',
  '78',
  'Celeste Lollis_Kizzy Brenner@MVC.com'],
 ['28',
  'Female',
  'Cordie Harnois',
  'MVC',
  '1501333',
  '94',
  'Gonzalo Ferebee_Tijuana Kropf@OOP.com'],
 ['29',
  'Female',
  'Taryn Brownlee',
  'OOP',
  '1511213',
  '72',
  'Cheri Kenney_Donna Yerby@DSA.com'],
 ['28',
  'Male',
  'Hubert Oliveras',
  'PF',
  '1521724',
  '91',
  'Eda Neathery_Jeannetta Golden@MVC.com'],
 ['29',
  'Female',
  'Naoma Fritts',
  'MVC',
  '1532260',
  '73',
  'Elenore Choy_Judie Chipps@DSA.com'],
 ['28',
  'Female',
  'Marylee Capasso',
  'Cloud',
  '1541030',
  '58',
  'Cordie Harnois_Celeste Lollis@PF.com'],
 ['29',
  'Female',
  'Annika Hoffman',
  'OOP',
  '1551846',
  '50',
  'Paris Hutton_Melani Engberg@DB.com'],
 ['28',
  'Female',
  'Jeannetta Golden',
  'OOP',
  '1562758',
  '40',
  'Jeannetta Golden_Billi Clore@Cloud.com'],
 ['29',
  'Female',
  'Cheri Kenney',
  'MVC',
  '1571310',
  '88',
  'Cordie Harnois_Lawanda Wohlwend@MVC.com'],
 ['29',
  'Female',
  'Jeannetta Golden',
  'PF',
  '1581770',
  '39',
  'Bonita Higuera_Santa Kerfien@OOP.com'],
 ['28',
  'Female',
  'Tamera Blakley',
  'PF',
  '1591554',
  '78',
  'Sebrina Maresca_Tijuana Kropf@OOP.com'],
 ['28',
  'Male',
  'Paris Hutton',
  'MVC',
  '1602777',
  '53',
  'Sheryll Towler_Loris Crossett@DSA.com'],
 ['28',
  'Male',
  'Marylee Capasso',
  'DB',
  '1611411',
  '96',
  'Annika Hoffman_Loris Crossett@PF.com'],
 ['28',
  'Male',
  'Anna Santos',
  'OOP',
  '1621905',
  '24',
  'Elenore Choy_Santa Kerfien@DB.com'],
 ['28',
  'Male',
  'Neda Briski',
  'DSA',
  '1632185',
  '93',
  'Clementina Menke_Toshiko Hillyard@Cloud.com'],
 ['29',
  'Female',
  'Michelle Ruggiero',
  'DB',
  '1642509',
  '45',
  'Hubert Oliveras_Marylee Capasso@DB.com'],
 ['28',
  'Female',
  'Neda Briski',
  'Cloud',
  '1651303',
  '74',
  'Ernest Rossbach_Donna Yerby@OOP.com'],
 ['28',
  'Female',
  'Loris Crossett',
  'DSA',
  '1662549',
  '86',
  'Paris Hutton_Latia Vanhoose@Cloud.com'],
 ['29',
  'Male',
  'Alberta Freund',
  'DB',
  '1671638',
  '98',
  'Clementina Menke_Jalisa Swenson@Cloud.com'],
 ['28',
  'Female',
  'Sebrina Maresca',
  'MVC',
  '1681804',
  '27',
  'Celeste Lollis_Ernest Rossbach@MVC.com'],
 ['28',
  'Male',
  'Celeste Lollis',
  'DB',
  '1692106',
  '36',
  'Neda Briski_Abram Nagao@MVC.com'],
 ['29',
  'Female',
  'Anna Santos',
  'DSA',
  '1702439',
  '64',
  'Naoma Fritts_Toshiko Hillyard@DB.com'],
 ['28',
  'Female',
  'Margene Moores',
  'DSA',
  '1712967',
  '41',
  'Tijuana Kropf_Sheryll Towler@DB.com'],
 ['28',
  'Female',
  'Priscila Tavernier',
  'DB',
  '1722388',
  '86',
  'Lawanda Wohlwend_Loris Crossett@DSA.com'],
 ['29',
  'Female',
  'Jc Andrepont',
  'MVC',
  '1731652',
  '74',
  'Hubert Oliveras_Michelle Ruggiero@DSA.com'],
 ['28',
  'Female',
  'Anna Santos',
  'DSA',
  '1741879',
  '89',
  'Nicole Harwood_Lawanda Wohlwend@DB.com'],
 ['29',
  'Female',
  'Lawanda Wohlwend',
  'MVC',
  '1751381',
  '75',
  'Jalisa Swenson_Nicole Harwood@OOP.com'],
 ['29',
  'Male',
  'Nicole Harwood',
  'MVC',
  '1761454',
  '34',
  'Taryn Brownlee_Billi Clore@DSA.com'],
 ['29',
  'Male',
  'Claude Panos',
  'DSA',
  '1771605',
  '50',
  'Claude Panos_Tamera Blakley@OOP.com'],
 ['29',
  'Male',
  'Dustin Feagins',
  'DB',
  '1782045',
  '81',
  'Cordie Harnois_Toshiko Hillyard@OOP.com'],
 ['29',
  'Male',
  'Toshiko Hillyard',
  'DSA',
  '1791364',
  '50',

In [0]:
# converting above modified RDD to DF

dfRDD = rdd1.toDF()
dfRDD.show()

+---+------+----------------+-----+------+---+--------------------+
| _1|    _2|              _3|   _4|    _5| _6|                  _7|
+---+------+----------------+-----+------+---+--------------------+
| 28|Female| Hubert Oliveras|   DB| 02984| 59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard|Cloud| 12899| 62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|   PF| 21267| 45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|   DB| 32877| 29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|  DSA| 41487| 41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|  MVC| 52771| 32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|  OOP| 61973| 69|Alberta Freund_El...|
| 28|Female|    Claude Panos|Cloud| 72409| 85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|  MVC| 81492| 64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|  OOP| 92882| 51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|  DSA|102285| 35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|   DB|111449| 53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|   DB|122502| 27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|  MVC|132110| 55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|   PF|141770| 42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|   DB|152159| 27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|  MVC|161771| 36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|  OOP|171660| 22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|   PF|182129| 56|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|   DB|192537| 62|Ernest Rossbach_M...|
+---+------+----------------+-----+------+---+--------------------+
only showing top 20 rows

In [0]:
# adding header to the DF
columns = header.split(',')
dfRDD = rdd1.toDF(columns)
# dfRDD.show()
dfRDD.printSchema()

root
 |-- age: string (nullable = true)
 |-- gender: string (nullable = true)
 |-- name: string (nullable = true)
 |-- course: string (nullable = true)
 |-- roll: string (nullable = true)
 |-- marks: string (nullable = true)
 |-- email: string (nullable = true)

In [0]:
# for changing the data types
from pyspark.sql.types import StructType, StructField, IntegerType, StringType

schemaa = StructType([
    StructField('age', IntegerType(), True),
    StructField('gender', StringType(), True),
    StructField('name', StringType(), True),
    StructField('course', StringType(), True),
    StructField('roll', StringType(), True),
    StructField('marks', IntegerType(), True),
    StructField('email', StringType(), True)
])


dfRDD = spark.createDataFrame(rdd1, schema=schemaa)
dfRDD.printSchema()
dfRDD.show() # some abnormality with databricks ignore the error

root
 |-- age: integer (nullable = true)
 |-- gender: string (nullable = true)
 |-- name: string (nullable = true)
 |-- course: string (nullable = true)
 |-- roll: string (nullable = true)
 |-- marks: integer (nullable = true)
 |-- email: string (nullable = true)

---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<command-1563385443433437> in <module>
     15 dfRDD = spark.createDataFrame(rdd1, schema=schemaa)
     16 dfRDD.printSchema()
---> 17 dfRDD.show() # some abnormality with databricks ignore the error

/databricks/spark/python/pyspark/sql/dataframe.py in show(self, n, truncate, vertical)
    500
    501         if isinstance(truncate, bool) and truncate:
--> 502             print(self._jdf.showString(n, 20, vertical))
    503         else:
    504             try:

/databricks/spark/python/lib/py4j-0.10.9.1-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1302
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    115     def deco(*a, **kw):
    116         try:
--> 117             return f(*a, **kw)
    118         except py4j.protocol.Py4JJavaError as e:
    119             converted = convert_exception(e.java_exception)

/databricks/spark/python/lib/py4j-0.10.9.1-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
    328                     format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling o1134.showString.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 15.0 failed 1 times, most recent failure: Lost task 0.0 in stage 15.0 (TID 19) (ip-10-172-209-198.us-west-2.compute.internal executor driver): org.apache.spark.api.python.PythonException: 'TypeError: field age: IntegerType can not accept object '28' in type <class 'str'>'. Full traceback below:
Traceback (most recent call last):
  File "/databricks/spark/python/pyspark/worker.py", line 752, in main
    process()
  File "/databricks/spark/python/pyspark/worker.py", line 744, in process
    serializer.dump_stream(out_iter, outfile)
  File "/databricks/spark/python/pyspark/serializers.py", line 264, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/databricks/spark/python/pyspark/util.py", line 74, in wrapper
    return f(*args, **kwargs)
  File "/databricks/spark/python/pyspark/sql/session.py", line 729, in prepare
    verify_func(obj)
  File "/databricks/spark/python/pyspark/sql/types.py", line 1411, in verify
    verify_value(obj)
  File "/databricks/spark/python/pyspark/sql/types.py", line 1392, in verify_struct
    verifier(v)
  File "/databricks/spark/python/pyspark/sql/types.py", line 1411, in verify
    verify_value(obj)
  File "/databricks/spark/python/pyspark/sql/types.py", line 1331, in verify_integer
    verify_acceptable_types(obj)
  File "/databricks/spark/python/pyspark/sql/types.py", line 1293, in verify_acceptable_types
    raise TypeError(new_msg("%s can not accept object %r in type %s"
TypeError: field age: IntegerType can not accept object '28' in type <class 'str'>

	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:693)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:855)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:837)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:646)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:491)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:759)
	at org.apache.spark.sql.execution.collect.UnsafeRowBatchUtils$.encodeUnsafeRows(UnsafeRowBatchUtils.scala:80)
	at org.apache.spark.sql.execution.collect.Collector.$anonfun$processFunc$1(Collector.scala:155)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$3(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$1(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:55)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:156)
	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:125)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.Task.run(Task.scala:95)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$13(Executor.scala:826)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1670)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:829)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:684)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2984)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2931)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2925)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2925)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1345)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1345)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1345)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3193)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3134)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3122)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:1107)
	at org.apache.spark.SparkContext.runJobInternal(SparkContext.scala:2628)
	at org.apache.spark.sql.execution.collect.Collector.runSparkJobs(Collector.scala:266)
	at org.apache.spark.sql.execution.collect.Collector.collect(Collector.scala:276)
	at org.apache.spark.sql.execution.collect.Collector$.collect(Collector.scala:81)
	at org.apache.spark.sql.execution.collect.Collector$.collect(Collector.scala:87)
	at org.apache.spark.sql.execution.collect.InternalRowFormat$.collect(cachedSparkResults.scala:75)
	at org.apache.spark.sql.execution.collect.InternalRowFormat$.collect(cachedSparkResults.scala:62)
	at org.apache.spark.sql.execution.ResultCacheManager.collectResult$1(ResultCacheManager.scala:587)
	at org.apache.spark.sql.execution.ResultCacheManager.computeResult(ResultCacheManager.scala:596)
	at org.apache.spark.sql.execution.ResultCacheManager.$anonfun$getOrComputeResultInternal$1(ResultCacheManager.scala:542)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResultInternal(ResultCacheManager.scala:541)
	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResult(ResultCacheManager.scala:438)
	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResult(ResultCacheManager.scala:417)
	at org.apache.spark.sql.execution.SparkPlan.executeCollectResult(SparkPlan.scala:422)
	at org.apache.spark.sql.Dataset.collectResult(Dataset.scala:3132)
	at org.apache.spark.sql.Dataset.collectFromPlan(Dataset.scala:3938)
	at org.apache.spark.sql.Dataset.$anonfun$head$1(Dataset.scala:2856)
	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3930)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$8(SQLExecution.scala:209)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:356)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:160)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:958)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:115)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:306)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3928)
	at org.apache.spark.sql.Dataset.head(Dataset.scala:2856)
	at org.apache.spark.sql.Dataset.take(Dataset.scala:3063)
	at org.apache.spark.sql.Dataset.getRows(Dataset.scala:293)
	at org.apache.spark.sql.Dataset.showString(Dataset.scala:332)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.spark.api.python.PythonException: 'TypeError: field age: IntegerType can not accept object '28' in type <class 'str'>'. Full traceback below:
Traceback (most recent call last):
  File "/databricks/spark/python/pyspark/worker.py", line 752, in main
    process()
  File "/databricks/spark/python/pyspark/worker.py", line 744, in process
    serializer.dump_stream(out_iter, outfile)
  File "/databricks/spark/python/pyspark/serializers.py", line 264, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/databricks/spark/python/pyspark/util.py", line 74, in wrapper
    return f(*args, **kwargs)
  File "/databricks/spark/python/pyspark/sql/session.py", line 729, in prepare
    verify_func(obj)
  File "/databricks/spark/python/pyspark/sql/types.py", line 1411, in verify
    verify_value(obj)
  File "/databricks/spark/python/pyspark/sql/types.py", line 1392, in verify_struct
    verifier(v)
  File "/databricks/spark/python/pyspark/sql/types.py", line 1411, in verify
    verify_value(obj)
  File "/databricks/spark/python/pyspark/sql/types.py", line 1331, in verify_integer
    verify_acceptable_types(obj)
  File "/databricks/spark/python/pyspark/sql/types.py", line 1293, in verify_acceptable_types
    raise TypeError(new_msg("%s can not accept object %r in type %s"
TypeError: field age: IntegerType can not accept object '28' in type <class 'str'>

	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:693)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:855)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:837)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:646)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:491)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:759)
	at org.apache.spark.sql.execution.collect.UnsafeRowBatchUtils$.encodeUnsafeRows(UnsafeRowBatchUtils.scala:80)
	at org.apache.spark.sql.execution.collect.Collector.$anonfun$processFunc$1(Collector.scala:155)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$3(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$1(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:55)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:156)
	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:125)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.Task.run(Task.scala:95)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$13(Executor.scala:826)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1670)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:829)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:684)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more

# Rectifying the Error

In [0]:
rdd2 = rdd1.map(lambda x: [int(x[0]), x[1], x[2], x[3], x[4], int(x[5]), x[6]])

In [0]:
from pyspark.sql.types import StructType, StructField, IntegerType, StringType

schemaa = StructType([
    StructField('age', IntegerType(), True),
    StructField('gender', StringType(), True),
    StructField('name', StringType(), True),
    StructField('course', StringType(), True),
    StructField('roll', StringType(), True),
    StructField('marks', IntegerType(), True),
    StructField('email', StringType(), True)
])

In [0]:
dfRDD = spark.createDataFrame(rdd2, schema=schemaa)
dfRDD.printSchema()
dfRDD.show()

root
 |-- age: integer (nullable = true)
 |-- gender: string (nullable = true)
 |-- name: string (nullable = true)
 |-- course: string (nullable = true)
 |-- roll: string (nullable = true)
 |-- marks: integer (nullable = true)
 |-- email: string (nullable = true)

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB| 02984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

# Select DF Columns

In [0]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName('Select Colums').getOrCreate()
df = spark.read.options(header='True', inferSchema='True').csv('/FileStore/tables/StudentData.csv')

df.show()

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

In [0]:
# method 1
df.select('name', 'gender').show() # select() is transformation and show()is action

+----------------+------+
|            name|gender|
+----------------+------+
| Hubert Oliveras|Female|
|Toshiko Hillyard|Female|
|  Celeste Lollis|  Male|
|    Elenore Choy|Female|
|  Sheryll Towler|  Male|
|  Margene Moores|  Male|
|     Neda Briski|  Male|
|    Claude Panos|Female|
|  Celeste Lollis|  Male|
|  Cordie Harnois|  Male|
|       Kena Wild|Female|
| Ernest Rossbach|  Male|
|  Latia Vanhoose|Female|
|  Latia Vanhoose|Female|
|     Neda Briski|  Male|
|  Latia Vanhoose|Female|
|  Loris Crossett|  Male|
|  Annika Hoffman|  Male|
|   Santa Kerfien|  Male|
|Mickey Cortright|Female|
+----------------+------+
only showing top 20 rows

In [0]:
# method 2
df.select(df.name, df.email).show()

+----------------+--------------------+
|            name|               email|
+----------------+--------------------+
| Hubert Oliveras|Annika Hoffman_Na...|
|Toshiko Hillyard|Margene Moores_Ma...|
|  Celeste Lollis|Jeannetta Golden_...|
|    Elenore Choy|Billi Clore_Mitzi...|
|  Sheryll Towler|Claude Panos_Judi...|
|  Margene Moores|Toshiko Hillyard_...|
|     Neda Briski|Alberta Freund_El...|
|    Claude Panos|Sheryll Towler_Al...|
|  Celeste Lollis|Nicole Harwood_Cl...|
|  Cordie Harnois|Judie Chipps_Clem...|
|       Kena Wild|Dustin Feagins_Ma...|
| Ernest Rossbach|Maybell Duguay_Ab...|
|  Latia Vanhoose|Latia Vanhoose_Mi...|
|  Latia Vanhoose|Eda Neathery_Nico...|
|     Neda Briski|Margene Moores_Mi...|
|  Latia Vanhoose|Claude Panos_Sant...|
|  Loris Crossett|Mitzi Seldon_Jenn...|
|  Annika Hoffman|Taryn Brownlee_Mi...|
|   Santa Kerfien|Judie Chipps_Tary...|
|Mickey Cortright|Ernest Rossbach_M...|
+----------------+--------------------+
only showing top 20 rows

In [0]:
# method 3
from pyspark.sql.functions import col

df.select(col('name'), col('marks')).show()

+----------------+-----+
|            name|marks|
+----------------+-----+
| Hubert Oliveras|   59|
|Toshiko Hillyard|   62|
|  Celeste Lollis|   45|
|    Elenore Choy|   29|
|  Sheryll Towler|   41|
|  Margene Moores|   32|
|     Neda Briski|   69|
|    Claude Panos|   85|
|  Celeste Lollis|   64|
|  Cordie Harnois|   51|
|       Kena Wild|   35|
| Ernest Rossbach|   53|
|  Latia Vanhoose|   27|
|  Latia Vanhoose|   55|
|     Neda Briski|   42|
|  Latia Vanhoose|   27|
|  Loris Crossett|   36|
|  Annika Hoffman|   22|
|   Santa Kerfien|   56|
|Mickey Cortright|   62|
+----------------+-----+
only showing top 20 rows

In [0]:
# method 4
df.select('*').show()

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

In [0]:
# method 5
df.columns

Out[49]: ['age', 'gender', 'name', 'course', 'roll', 'marks', 'email']

In [0]:
df.columns[2]

Out[50]: 'name'

In [0]:
df.select(df.columns[4], df.columns[2]).show()

+------+----------------+
|  roll|            name|
+------+----------------+
|  2984| Hubert Oliveras|
| 12899|Toshiko Hillyard|
| 21267|  Celeste Lollis|
| 32877|    Elenore Choy|
| 41487|  Sheryll Towler|
| 52771|  Margene Moores|
| 61973|     Neda Briski|
| 72409|    Claude Panos|
| 81492|  Celeste Lollis|
| 92882|  Cordie Harnois|
|102285|       Kena Wild|
|111449| Ernest Rossbach|
|122502|  Latia Vanhoose|
|132110|  Latia Vanhoose|
|141770|     Neda Briski|
|152159|  Latia Vanhoose|
|161771|  Loris Crossett|
|171660|  Annika Hoffman|
|182129|   Santa Kerfien|
|192537|Mickey Cortright|
+------+----------------+
only showing top 20 rows

In [0]:
# method 6
from pyspark.sql.functions import col
df.select(df.columns[4], 'name', df.course, col('marks')).show() # by this way we can filter the columns

+------+----------------+------+-----+
|  roll|            name|course|marks|
+------+----------------+------+-----+
|  2984| Hubert Oliveras|    DB|   59|
| 12899|Toshiko Hillyard| Cloud|   62|
| 21267|  Celeste Lollis|    PF|   45|
| 32877|    Elenore Choy|    DB|   29|
| 41487|  Sheryll Towler|   DSA|   41|
| 52771|  Margene Moores|   MVC|   32|
| 61973|     Neda Briski|   OOP|   69|
| 72409|    Claude Panos| Cloud|   85|
| 81492|  Celeste Lollis|   MVC|   64|
| 92882|  Cordie Harnois|   OOP|   51|
|102285|       Kena Wild|   DSA|   35|
|111449| Ernest Rossbach|    DB|   53|
|122502|  Latia Vanhoose|    DB|   27|
|132110|  Latia Vanhoose|   MVC|   55|
|141770|     Neda Briski|    PF|   42|
|152159|  Latia Vanhoose|    DB|   27|
|161771|  Loris Crossett|   MVC|   36|
|171660|  Annika Hoffman|   OOP|   22|
|182129|   Santa Kerfien|    PF|   56|
|192537|Mickey Cortright|    DB|   62|
+------+----------------+------+-----+
only showing top 20 rows

# Spark DF WithColumn

In [0]:
# using withColumn() we can add/ change datatype of particular column

from pyspark.sql import SparkSession

spark = SparkSession.builder.appName('WithColumn').getOrCreate()
df = spark.read.options(header='True', inferSchema='True').csv('/FileStore/tables/StudentData.csv')

df.printSchema()
df.show()

root
 |-- age: integer (nullable = true)
 |-- gender: string (nullable = true)
 |-- name: string (nullable = true)
 |-- course: string (nullable = true)
 |-- roll: integer (nullable = true)
 |-- marks: integer (nullable = true)
 |-- email: string (nullable = true)

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

In [0]:
from pyspark.sql.functions import col
conDF = df.withColumn('roll', col('roll').cast('String'))
conDF.printSchema()

root
 |-- age: integer (nullable = true)
 |-- gender: string (nullable = true)
 |-- name: string (nullable = true)
 |-- course: string (nullable = true)
 |-- roll: string (nullable = true)
 |-- marks: integer (nullable = true)
 |-- email: string (nullable = true)

In [0]:
df.show()

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

In [0]:
from pyspark.sql.functions import col

# df.withColumn('marks', df.marks + 10).show()
# df.withColumn('marks', df[5] + 10).show()
df.withColumn('marks', col('marks') + 10).show()

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   69|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   72|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   55|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   39|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   51|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   42|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   79|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   95|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   74|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   61|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   45|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   63|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   37|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   65|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   52|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   37|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   46|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   32|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   66|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   72|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

In [0]:
df.withColumn('updated marks', df[5] + 10).show()

+---+------+----------------+------+------+-----+--------------------+-------------+
|age|gender|            name|course|  roll|marks|               email|updated marks|
+---+------+----------------+------+------+-----+--------------------+-------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|           69|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|           72|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|           55|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|           39|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|           51|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|           42|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|           79|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|           95|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|           74|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|           61|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|           45|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|           63|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|           37|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|           65|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|           52|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|           37|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|           46|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|           32|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|           66|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|           72|
+---+------+----------------+------+------+-----+--------------------+-------------+
only showing top 20 rows

In [0]:
from pyspark.sql.functions import lit
df.withColumn('country', lit('USA')).show()

+---+------+----------------+------+------+-----+--------------------+-------+
|age|gender|            name|course|  roll|marks|               email|country|
+---+------+----------------+------+------+-----+--------------------+-------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|    USA|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|    USA|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|    USA|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|    USA|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|    USA|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|    USA|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|    USA|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|    USA|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|    USA|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|    USA|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|    USA|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|    USA|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|    USA|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|    USA|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|    USA|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|    USA|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|    USA|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|    USA|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|    USA|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|    USA|
+---+------+----------------+------+------+-----+--------------------+-------+
only showing top 20 rows

In [0]:
updatedDF = df.withColumn('updated marks', df.marks + 10).withColumn('country', lit('USA'))

In [0]:
df.show()

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

In [0]:
updatedDF.show()

+---+------+----------------+------+------+-----+--------------------+-------------+-------+
|age|gender|            name|course|  roll|marks|               email|updated marks|country|
+---+------+----------------+------+------+-----+--------------------+-------------+-------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|           69|    USA|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|           72|    USA|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|           55|    USA|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|           39|    USA|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|           51|    USA|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|           42|    USA|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|           79|    USA|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|           95|    USA|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|           74|    USA|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|           61|    USA|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|           45|    USA|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|           63|    USA|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|           37|    USA|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|           65|    USA|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|           52|    USA|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|           37|    USA|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|           46|    USA|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|           32|    USA|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|           66|    USA|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|           72|    USA|
+---+------+----------------+------+------+-----+--------------------+-------------+-------+
only showing top 20 rows

# Spark DF withColumnRenamed and Alias

In [0]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lit

spark = SparkSession.builder.appName('withColumnRenamed').getOrCreate()
df = spark.read.options(header='True', inferSchema='True').csv('/FileStore/tables/StudentData.csv')
df.show()

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

In [0]:
df.withColumnRenamed('gender', 'sex').show() # here we can change the column name permanently by adding an new dataframe

+---+------+----------------+------+------+-----+--------------------+
|age|   sex|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

In [0]:
df.select(col('name').alias('Full Name')).show() # alias() will not change column name permanently it just for reading purpose

+----------------+
|       Full Name|
+----------------+
| Hubert Oliveras|
|Toshiko Hillyard|
|  Celeste Lollis|
|    Elenore Choy|
|  Sheryll Towler|
|  Margene Moores|
|     Neda Briski|
|    Claude Panos|
|  Celeste Lollis|
|  Cordie Harnois|
|       Kena Wild|
| Ernest Rossbach|
|  Latia Vanhoose|
|  Latia Vanhoose|
|     Neda Briski|
|  Latia Vanhoose|
|  Loris Crossett|
|  Annika Hoffman|
|   Santa Kerfien|
|Mickey Cortright|
+----------------+
only showing top 20 rows

# Spark DF Filter rows

In [0]:
df.filter(df.course == 'DB').show()
df.filter(df.course == 'DB').count()

+---+------+-----------------+------+-------+-----+--------------------+
|age|gender|             name|course|   roll|marks|               email|
+---+------+-----------------+------+-------+-----+--------------------+
| 28|Female|  Hubert Oliveras|    DB|   2984|   59|Annika Hoffman_Na...|
| 29|Female|     Elenore Choy|    DB|  32877|   29|Billi Clore_Mitzi...|
| 29|  Male|  Ernest Rossbach|    DB| 111449|   53|Maybell Duguay_Ab...|
| 28|Female|   Latia Vanhoose|    DB| 122502|   27|Latia Vanhoose_Mi...|
| 29|Female|   Latia Vanhoose|    DB| 152159|   27|Claude Panos_Sant...|
| 28|Female| Mickey Cortright|    DB| 192537|   62|Ernest Rossbach_M...|
| 28|Female|      Anna Santos|    DB| 311589|   79|Celeste Lollis_Mi...|
| 28|  Male|    Kizzy Brenner|    DB| 381712|   36|Paris Hutton_Kena...|
| 28|  Male| Toshiko Hillyard|    DB| 392218|   47|Leontine Phillips...|
| 29|  Male|     Paris Hutton|    DB| 481229|   57|Clementina Menke_...|
| 28|Female| Mickey Cortright|    DB| 551389|   43|Tijuana Kropf_Jen...|
| 28|Female|Leontine Phillips|    DB| 602404|   48|Neda Briski_Cheri...|
| 28|Female|  Hubert Oliveras|    DB| 771081|   79|Kizzy Brenner_Dus...|
| 29|Female|     Elenore Choy|    DB| 811824|   55|Maybell Duguay_Me...|
| 29|  Male| Clementina Menke|    DB| 882200|   76|Michelle Ruggiero...|
| 29|Female|  Sebrina Maresca|    DB| 922210|   54|Toshiko Hillyard_...|
| 29|  Male|     Naoma Fritts|    DB| 931295|   79|Hubert Oliveras_S...|
| 28|  Male|   Annika Hoffman|    DB|1031544|   44|Dustin Feagins_So...|
| 28|  Male|   Nicole Harwood|    DB|1211495|   28|Melani Engberg_Jc...|
| 29|Female|     Claude Panos|    DB|1222887|   75|Hubert Oliveras_S...|
+---+------+-----------------+------+-------+-----+--------------------+
only showing top 20 rows

Out[110]: 157

In [0]:
df.filter(col('course') == 'DB').show()

+---+------+-----------------+------+-------+-----+--------------------+
|age|gender|             name|course|   roll|marks|               email|
+---+------+-----------------+------+-------+-----+--------------------+
| 28|Female|  Hubert Oliveras|    DB|   2984|   59|Annika Hoffman_Na...|
| 29|Female|     Elenore Choy|    DB|  32877|   29|Billi Clore_Mitzi...|
| 29|  Male|  Ernest Rossbach|    DB| 111449|   53|Maybell Duguay_Ab...|
| 28|Female|   Latia Vanhoose|    DB| 122502|   27|Latia Vanhoose_Mi...|
| 29|Female|   Latia Vanhoose|    DB| 152159|   27|Claude Panos_Sant...|
| 28|Female| Mickey Cortright|    DB| 192537|   62|Ernest Rossbach_M...|
| 28|Female|      Anna Santos|    DB| 311589|   79|Celeste Lollis_Mi...|
| 28|  Male|    Kizzy Brenner|    DB| 381712|   36|Paris Hutton_Kena...|
| 28|  Male| Toshiko Hillyard|    DB| 392218|   47|Leontine Phillips...|
| 29|  Male|     Paris Hutton|    DB| 481229|   57|Clementina Menke_...|
| 28|Female| Mickey Cortright|    DB| 551389|   43|Tijuana Kropf_Jen...|
| 28|Female|Leontine Phillips|    DB| 602404|   48|Neda Briski_Cheri...|
| 28|Female|  Hubert Oliveras|    DB| 771081|   79|Kizzy Brenner_Dus...|
| 29|Female|     Elenore Choy|    DB| 811824|   55|Maybell Duguay_Me...|
| 29|  Male| Clementina Menke|    DB| 882200|   76|Michelle Ruggiero...|
| 29|Female|  Sebrina Maresca|    DB| 922210|   54|Toshiko Hillyard_...|
| 29|  Male|     Naoma Fritts|    DB| 931295|   79|Hubert Oliveras_S...|
| 28|  Male|   Annika Hoffman|    DB|1031544|   44|Dustin Feagins_So...|
| 28|  Male|   Nicole Harwood|    DB|1211495|   28|Melani Engberg_Jc...|
| 29|Female|     Claude Panos|    DB|1222887|   75|Hubert Oliveras_S...|
+---+------+-----------------+------+-------+-----+--------------------+
only showing top 20 rows

In [0]:
df.filter((df.course == 'DB') & (df.marks > 50)).show()

+---+------+------------------+------+-------+-----+--------------------+
|age|gender|              name|course|   roll|marks|               email|
+---+------+------------------+------+-------+-----+--------------------+
| 28|Female|   Hubert Oliveras|    DB|   2984|   59|Annika Hoffman_Na...|
| 29|  Male|   Ernest Rossbach|    DB| 111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Mickey Cortright|    DB| 192537|   62|Ernest Rossbach_M...|
| 28|Female|       Anna Santos|    DB| 311589|   79|Celeste Lollis_Mi...|
| 29|  Male|      Paris Hutton|    DB| 481229|   57|Clementina Menke_...|
| 28|Female|   Hubert Oliveras|    DB| 771081|   79|Kizzy Brenner_Dus...|
| 29|Female|      Elenore Choy|    DB| 811824|   55|Maybell Duguay_Me...|
| 29|  Male|  Clementina Menke|    DB| 882200|   76|Michelle Ruggiero...|
| 29|Female|   Sebrina Maresca|    DB| 922210|   54|Toshiko Hillyard_...|
| 29|  Male|      Naoma Fritts|    DB| 931295|   79|Hubert Oliveras_S...|
| 29|Female|      Claude Panos|    DB|1222887|   75|Hubert Oliveras_S...|
| 29|Female| Leontine Phillips|    DB|1432252|   67|Billi Clore_Shery...|
| 28|Female|   Gonzalo Ferebee|    DB|1451513|   69|Claude Panos_Tame...|
| 28|  Male|   Marylee Capasso|    DB|1611411|   96|Annika Hoffman_Lo...|
| 29|  Male|    Alberta Freund|    DB|1671638|   98|Clementina Menke_...|
| 28|Female|Priscila Tavernier|    DB|1722388|   86|Lawanda Wohlwend_...|
| 29|  Male|    Dustin Feagins|    DB|1782045|   81|Cordie Harnois_To...|
| 29|  Male|     Tijuana Kropf|    DB|1882795|   92|Hubert Oliveras_E...|
| 28|  Male|   Ernest Rossbach|    DB|1901492|   54|Latia Vanhoose_Jc...|
| 29|Female| Leontine Phillips|    DB|1972893|   64|Marylee Capasso_E...|
+---+------+------------------+------+-------+-----+--------------------+
only showing top 20 rows

In [0]:
courses = ['DB', 'Cloud', 'OOP', 'DSA']
df.filter(df.course.isin(courses)).show()

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
| 28|Female|       Kena Wild| Cloud|221750|   60|Mitzi Seldon_Jenn...|
| 28|Female|    Jc Andrepont|   DSA|232060|   58|Billi Clore_Abram...|
| 29|Female|     Anna Santos| Cloud|242254|   68|Jc Andrepont_Hube...|
| 28|Female|  Alberta Freund|   OOP|251805|   83|Annika Hoffman_Sh...|
| 28|Female|  Maybell Duguay| Cloud|261439|   20|Nicole Harwood_Ju...|
| 29|Female|    Paris Hutton|   DSA|271472|   99|Sheryll Towler_Al...|
| 29|Female|    Cheri Kenney| Cloud|281408|   43|Annika Hoffman_Me...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

In [0]:
df.filter(df.course.startswith('D')).show()

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
| 28|Female|    Jc Andrepont|   DSA|232060|   58|Billi Clore_Abram...|
| 29|Female|    Paris Hutton|   DSA|271472|   99|Sheryll Towler_Al...|
| 28|Female|  Dustin Feagins|   DSA|291984|   82|Abram Nagao_Kena ...|
| 28|Female|     Anna Santos|    DB|311589|   79|Celeste Lollis_Mi...|
| 28|Female|Mickey Cortright|   DSA|342003|   44|Mitzi Seldon_Jean...|
| 28|  Male|   Kizzy Brenner|    DB|381712|   36|Paris Hutton_Kena...|
| 28|  Male|Toshiko Hillyard|    DB|392218|   47|Leontine Phillips...|
| 29|Female|     Anna Santos|   DSA|411479|   42|Kena Wild_Mitzi S...|
| 28|Female|  Maybell Duguay|   DSA|452141|   29|Leontine Phillips...|
| 29|  Male|    Paris Hutton|    DB|481229|   57|Clementina Menke_...|
| 29|Female|    Paris Hutton|   DSA|492159|   60|Nicole Harwood_Ma...|
| 28|Female|Mickey Cortright|    DB|551389|   43|Tijuana Kropf_Jen...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

In [0]:
df.filter(df.course.endswith('A')).show()

+---+------+----------------+------+-------+-----+--------------------+
|age|gender|            name|course|   roll|marks|               email|
+---+------+----------------+------+-------+-----+--------------------+
| 28|  Male|  Sheryll Towler|   DSA|  41487|   41|Claude Panos_Judi...|
| 29|Female|       Kena Wild|   DSA| 102285|   35|Dustin Feagins_Ma...|
| 28|Female|    Jc Andrepont|   DSA| 232060|   58|Billi Clore_Abram...|
| 29|Female|    Paris Hutton|   DSA| 271472|   99|Sheryll Towler_Al...|
| 28|Female|  Dustin Feagins|   DSA| 291984|   82|Abram Nagao_Kena ...|
| 28|Female|Mickey Cortright|   DSA| 342003|   44|Mitzi Seldon_Jean...|
| 29|Female|     Anna Santos|   DSA| 411479|   42|Kena Wild_Mitzi S...|
| 28|Female|  Maybell Duguay|   DSA| 452141|   29|Leontine Phillips...|
| 29|Female|    Paris Hutton|   DSA| 492159|   60|Nicole Harwood_Ma...|
| 29|  Male|  Celeste Lollis|   DSA| 562065|   85|Jc Andrepont_Mela...|
| 29|  Male|  Maybell Duguay|   DSA| 592061|   83|Eda Neathery_Jenn...|
| 28|  Male|    Mitzi Seldon|   DSA| 622981|   45|Lawanda Wohlwend_...|
| 28|Female|  Jenna Montague|   DSA| 691564|   26|Mitzi Seldon_Sebr...|
| 28|Female|  Celeste Lollis|   DSA| 731879|   76|Hubert Oliveras_G...|
| 28|  Male|  Sheryll Towler|   DSA| 831562|   59|Kena Wild_Gonzalo...|
| 28|Female|  Sheryll Towler|   DSA| 871967|   64|Michelle Ruggiero...|
| 28|  Male|  Margene Moores|   DSA| 892010|   93|Anna Santos_Naoma...|
| 28|Female|  Somer Stoecker|   DSA| 901958|   64|Kizzy Brenner_Jc ...|
| 28|Female|Lawanda Wohlwend|   DSA| 951686|   60|Loris Crossett_Ni...|
| 28|  Male|  Jenna Montague|   DSA|1002103|   36|Melani Engberg_Hu...|
+---+------+----------------+------+-------+-----+--------------------+
only showing top 20 rows

In [0]:
df.filter(df.name.endswith('Wild')).show()

+---+------+---------+------+-------+-----+--------------------+
|age|gender|     name|course|   roll|marks|               email|
+---+------+---------+------+-------+-----+--------------------+
| 29|Female|Kena Wild|   DSA| 102285|   35|Dustin Feagins_Ma...|
| 28|Female|Kena Wild| Cloud| 221750|   60|Mitzi Seldon_Jenn...|
| 28|  Male|Kena Wild|    DB|2031530|   93|Jc Andrepont_Jc A...|
| 28|Female|Kena Wild|    PF|2931712|   52|Melani Engberg_Le...|
| 28|Female|Kena Wild|    PF|3291691|   96|Tamera Blakley_Na...|
| 28|Female|Kena Wild|    DB|4431030|   59|Paris Hutton_Cher...|
| 28|Female|Kena Wild|    DB|5001412|   53|Annika Hoffman_Ja...|
| 29|  Male|Kena Wild|   DSA|6092008|   76|Sheryll Towler_An...|
| 28|Female|Kena Wild|   DSA|6201485|   85|Niki Klimek_Cleme...|
| 28|Female|Kena Wild|   DSA|6831241|   94|Loris Crossett_Le...|
| 29|Female|Kena Wild|    DB|6911600|   73|Maybell Duguay_La...|
| 29|Female|Kena Wild|   DSA|7621891|   69|Marylee Capasso_M...|
| 28|Female|Kena Wild|   MVC|7781364|   75|Claude Panos_Sebr...|
| 29|  Male|Kena Wild|    PF|7862418|   56|Clementina Menke_...|
| 29|  Male|Kena Wild|    PF|8331264|   46|Marylee Capasso_C...|
| 28|  Male|Kena Wild|    DB|8471833|   36|Tamera Blakley_Je...|
| 28|Female|Kena Wild|   MVC|9401194|   24|Niki Klimek_Miche...|
| 29|  Male|Kena Wild|   MVC|9611287|   76|Cordie Harnois_Mi...|
| 29|  Male|Kena Wild|   DSA|9662661|   41|Latia Vanhoose_Se...|
| 28|  Male|Kena Wild|   DSA|9891274|   85|Donna Yerby_Leont...|
+---+------+---------+------+-------+-----+--------------------+

In [0]:
df.filter(df.name.contains('se')).show() # it will returen every thing that contains 'se' in it

+---+------+--------------+------+-------+-----+--------------------+
|age|gender|          name|course|   roll|marks|               email|
+---+------+--------------+------+-------+-----+--------------------+
| 28|Female|Latia Vanhoose|    DB| 122502|   27|Latia Vanhoose_Mi...|
| 29|Female|Latia Vanhoose|   MVC| 132110|   55|Eda Neathery_Nico...|
| 29|Female|Latia Vanhoose|    DB| 152159|   27|Claude Panos_Sant...|
| 29|  Male|Loris Crossett|   MVC| 161771|   36|Mitzi Seldon_Jenn...|
| 29|Female|Loris Crossett|    PF| 201487|   96|Elenore Choy_Lati...|
| 28|Female|Loris Crossett|    PF| 332739|   62|Michelle Ruggiero...|
| 29|  Male|Loris Crossett|    PF| 911593|   46|Gonzalo Ferebee_M...|
| 28|Female|Loris Crossett|   DSA|1662549|   86|Paris Hutton_Lati...|
| 29|  Male|Latia Vanhoose| Cloud|1832268|   60|Marylee Capasso_S...|
| 29|  Male|Latia Vanhoose|   OOP|2372748|   94|Latia Vanhoose_La...|
| 28|Female|Loris Crossett|   OOP|2691881|   29|Maybell Duguay_Ni...|
| 28|  Male|Loris Crossett|   OOP|2852490|   25|Loris Crossett_Do...|
| 29|Female|Latia Vanhoose|    PF|2861854|   42|Claude Panos_Nico...|
| 29|  Male|Latia Vanhoose|   MVC|2992281|   90|Elenore Choy_Cord...|
| 29|Female|Latia Vanhoose|   MVC|3091650|   30|Cordie Harnois_Se...|
| 28|Female|Loris Crossett|   OOP|3502780|   30|Jenna Montague_Co...|
| 28|Female|Loris Crossett|    PF|3531684|   84|Dustin Feagins_Ta...|
| 29|  Male|Loris Crossett|   OOP|3592529|   80|Annika Hoffman_To...|
| 29|Female|Latia Vanhoose|   OOP|3841395|   26|Kizzy Brenner_Eda...|
| 28|Female|Loris Crossett|    PF|3861248|   94|Dustin Feagins_Ch...|
+---+------+--------------+------+-------+-----+--------------------+
only showing top 20 rows

In [0]:
df.filter(df.name.like('%e_')).show() # works same as SQL

+---+------+------------------+------+------+-----+--------------------+
|age|gender|              name|course|  roll|marks|               email|
+---+------+------------------+------+------+-----+--------------------+
| 28|  Male|    Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|    Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 29|  Male|     Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
| 29|Female|       Niki Klimek|    PF|211508|   23|Cordie Harnois_Ju...|
| 29|Female|      Cheri Kenney| Cloud|281408|   43|Annika Hoffman_Me...|
| 28|Female|      Cheri Kenney|   MVC|321816|   24|Kena Wild_Michell...|
| 28|  Male|     Kizzy Brenner|    DB|381712|   36|Paris Hutton_Kena...|
| 28|Female|     Kizzy Brenner| Cloud|402409|   27|Ernest Rossbach_G...|
| 29|Female|    Somer Stoecker| Cloud|442028|   34|Taryn Brownlee_Ta...|
| 28|  Male|    Margene Moores|    PF|531530|   53|Cheri Kenney_Mela...|
| 28|Female|    Somer Stoecker| Cloud|612490|   82|Sebrina Maresca_G...|
| 28|  Male|Priscila Tavernier|    PF|642594|   27|Marylee Capasso_C...|
| 29|  Male|    Tamera Blakley|   MVC|651649|   92|Latia Vanhoose_To...|
| 28|  Male|    Sheryll Towler|   MVC|661079|   89|Tijuana Kropf_Mic...|
| 29|  Male|    Sheryll Towler|    PF|682533|   42|Billi Clore_Anna ...|
| 29|  Male|  Jeannetta Golden|   MVC|741875|   57|Sheryll Towler_Ch...|
| 29|Female|    Margene Moores|   MVC|761843|   48|Ernest Rossbach_M...|
| 28|  Male|    Sheryll Towler|   DSA|831562|   59|Kena Wild_Gonzalo...|
| 28|Female|     Santa Kerfien| Cloud|851620|   34|Melani Engberg_Sh...|
| 29|Female|    Taryn Brownlee|   MVC|861849|   39|Billi Clore_Toshi...|
+---+------+------------------+------+------+-----+--------------------+
only showing top 20 rows

# Quiz (select, withColumn, filter)

In [0]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lit

spark = SparkSession.builder.appName('Q1').getOrCreate()
df = spark.read.options(header='True', inferSchema='True').csv('gender')
df.show()

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

In [0]:
df1 = df.withColumn('total_marks', lit(120))
df1.show()

+---+------+----------------+------+------+-----+--------------------+-----------+
|age|gender|            name|course|  roll|marks|               email|total_marks|
+---+------+----------------+------+------+-----+--------------------+-----------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|        120|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|        120|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|        120|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|        120|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|        120|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|        120|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|        120|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|        120|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|        120|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|        120|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|        120|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|        120|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|        120|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|        120|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|        120|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|        120|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|        120|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|        120|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|        120|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|        120|
+---+------+----------------+------+------+-----+--------------------+-----------+
only showing top 20 rows

In [0]:
df2 = df1.withColumn('average', (col('marks') / col('total_marks')) * 100)
df2.show()

+---+------+----------------+------+------+-----+--------------------+-----------+------------------+
|age|gender|            name|course|  roll|marks|               email|total_marks|           average|
+---+------+----------------+------+------+-----+--------------------+-----------+------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|        120|49.166666666666664|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|        120| 51.66666666666667|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|        120|              37.5|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|        120|24.166666666666668|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|        120|34.166666666666664|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|        120|26.666666666666668|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|        120| 57.49999999999999|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|        120| 70.83333333333334|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|        120|53.333333333333336|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|        120|              42.5|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|        120|29.166666666666668|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|        120|44.166666666666664|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|        120|              22.5|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|        120| 45.83333333333333|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|        120|              35.0|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|        120|              22.5|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|        120|              30.0|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|        120|18.333333333333332|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|        120|46.666666666666664|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|        120| 51.66666666666667|
+---+------+----------------+------+------+-----+--------------------+-----------+------------------+
only showing top 20 rows

In [0]:
df_OOP = df2.filter((col('course') == 'OOP') & (col('average') > 80))
df_OOP.show()

+---+------+------------------+------+-------+-----+--------------------+-----------+-----------------+
|age|gender|              name|course|   roll|marks|               email|total_marks|          average|
+---+------+------------------+------+-------+-----+--------------------+-----------+-----------------+
| 28|  Male|    Jenna Montague|   OOP|3331161|   98|Leontine Phillips...|        120|81.66666666666667|
| 29|Female|Priscila Tavernier|   OOP|3902993|   99|Celeste Lollis_Bi...|        120|             82.5|
| 28|Female|      Judie Chipps|   OOP|5451977|   99|Tamera Blakley_Mi...|        120|             82.5|
| 29|  Male|    Margene Moores|   OOP|5621072|   97|Sheryll Towler_Ma...|        120|80.83333333333333|
| 29|  Male|      Jc Andrepont|   OOP|8022618|   97|Cordie Harnois_Ja...|        120|80.83333333333333|
| 28|  Male|    Loris Crossett|   OOP|8172914|   98|Paris Hutton_Pari...|        120|81.66666666666667|
| 28|  Male|    Loris Crossett|   OOP|9692316|   99|Judie Chipps_Mich...|        120|             82.5|
+---+------+------------------+------+-------+-----+--------------------+-----------+-----------------+

In [0]:
# df_Cloud = df2.filter((df.course == 'Cloud') & (df.average > 60))
df_Cloud = df2.filter((col('course') == 'Cloud') & (col('average') > 60))

df_Cloud.show()

+---+------+-----------------+------+-------+-----+--------------------+-----------+-----------------+
|age|gender|             name|course|   roll|marks|               email|total_marks|          average|
+---+------+-----------------+------+-------+-----+--------------------+-----------+-----------------+
| 28|Female|     Claude Panos| Cloud|  72409|   85|Sheryll Towler_Al...|        120|70.83333333333334|
| 29|  Male|      Billi Clore| Cloud| 512047|   76|Taryn Brownlee_Ju...|        120|63.33333333333333|
| 28|Female|   Somer Stoecker| Cloud| 612490|   82|Sebrina Maresca_G...|        120|68.33333333333333|
| 29|Female|     Judie Chipps| Cloud| 632793|   75|Tijuana Kropf_Ele...|        120|             62.5|
| 29|Female|     Eda Neathery| Cloud|1011971|   91|Margene Moores_El...|        120|75.83333333333333|
| 28|  Male|   Bonita Higuera| Cloud|1312294|   94|Eda Neathery_Pris...|        120|78.33333333333333|
| 29|Female|  Hubert Oliveras| Cloud|1392791|   94|Anna Santos_Alber...|        120|78.33333333333333|
| 28|Female|      Neda Briski| Cloud|1651303|   74|Ernest Rossbach_D...|        120|61.66666666666667|
| 28|Female|   Melani Engberg| Cloud|1872667|   99|Alberta Freund_Ni...|        120|             82.5|
| 28|Female|     Paris Hutton| Cloud|2051881|   79|Melani Engberg_Ma...|        120|65.83333333333333|
| 28|Female|     Eda Neathery| Cloud|2071302|   95|Latia Vanhoose_Do...|        120|79.16666666666666|
| 28|  Male|      Neda Briski| Cloud|2092176|   81|Celeste Lollis_Ma...|        120|             67.5|
| 28|Female|    Tijuana Kropf| Cloud|2121632|   78|Michelle Ruggiero...|        120|             65.0|
| 28|Female|   Jenna Montague| Cloud|2402240|   96|Annika Hoffman_Du...|        120|             80.0|
| 29|Female|   Dustin Feagins| Cloud|2421900|   89|Niki Klimek_Latia...|        120|74.16666666666667|
| 28|Female|  Ernest Rossbach| Cloud|2602027|   83|Alberta Freund_Go...|        120|69.16666666666667|
| 28|  Male|Leontine Phillips| Cloud|3011586|   76|Dustin Feagins_Al...|        120|63.33333333333333|
| 29|Female|  Sebrina Maresca| Cloud|3261159|   97|Maybell Duguay_Ja...|        120|80.83333333333333|
| 28|  Male| Clementina Menke| Cloud|3352508|   95|Naoma Fritts_Mick...|        120|79.16666666666666|
| 28|  Male|    Kizzy Brenner| Cloud|3581303|   80|Margene Moores_Ta...|        120|66.66666666666666|
+---+------+-----------------+------+-------+-----+--------------------+-----------+-----------------+
only showing top 20 rows

In [0]:
df.select(col('name'), col('marks')).show()

+----------------+-----+
|            name|marks|
+----------------+-----+
| Hubert Oliveras|   59|
|Toshiko Hillyard|   62|
|  Celeste Lollis|   45|
|    Elenore Choy|   29|
|  Sheryll Towler|   41|
|  Margene Moores|   32|
|     Neda Briski|   69|
|    Claude Panos|   85|
|  Celeste Lollis|   64|
|  Cordie Harnois|   51|
|       Kena Wild|   35|
| Ernest Rossbach|   53|
|  Latia Vanhoose|   27|
|  Latia Vanhoose|   55|
|     Neda Briski|   42|
|  Latia Vanhoose|   27|
|  Loris Crossett|   36|
|  Annika Hoffman|   22|
|   Santa Kerfien|   56|
|Mickey Cortright|   62|
+----------------+-----+
only showing top 20 rows

# Spark DF (Count, Distinct, Duplicate)

In [0]:
df.show()

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

In [0]:
print('Total no of enrolments: ', df.count())

print('Total no of enrolments for DB: ', df.filter(df.course == 'DB').count())

Total no of enrolments:  1000
Total no of enrolments for DB:  157

In [0]:
df.select(df.gender, df.age).distinct().show()# it will give only unique values

+------+---+
|gender|age|
+------+---+
|Female| 29|
|Female| 28|
|  Male| 28|
|  Male| 29|
+------+---+

In [0]:
df.dropDuplicates(['gender','course']).show()

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 28|Female|  Alberta Freund|   OOP|251805|   83|Annika Hoffman_Sh...|
| 29|Female|  Loris Crossett|    PF|201487|   96|Elenore Choy_Lati...|
| 29|  Male|     Billi Clore| Cloud|512047|   76|Taryn Brownlee_Ju...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
+---+------+----------------+------+------+-----+--------------------+

# Quiz (Distinct, Duplicate)

In [0]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName('Distinct and Duplicate').getOrCreate()
df = spark.read.options(header='True', inferschema='True').csv('/FileStore/tables/StudentData.csv')

In [0]:
df1 = df.dropDuplicates(['age', 'gender', 'course'])

print(df1.count())
df1.show()

24
+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|
| 28|Female|    Jc Andrepont|   DSA|232060|   58|Billi Clore_Abram...|
| 28|Female|    Cheri Kenney|   MVC|321816|   24|Kena Wild_Michell...|
| 28|Female|  Alberta Freund|   OOP|251805|   83|Annika Hoffman_Sh...|
| 28|Female|  Loris Crossett|    PF|332739|   62|Michelle Ruggiero...|
| 28|  Male|  Annika Hoffman| Cloud|722193|   55|Taryn Brownlee_El...|
| 28|  Male|   Kizzy Brenner|    DB|381712|   36|Paris Hutton_Kena...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|Female|    Claude Panos|   OOP|542821|   28|Hubert Oliveras_P...|
| 29|Female|  Loris Crossett|    PF|201487|   96|Elenore Choy_Lati...|
| 29|  Male|     Billi Clore| Cloud|512047|   76|Taryn Brownlee_Ju...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

In [0]:
df2 = df.select(df.age, df.gender, df.course).distinct()

print(df2.count())
df2.show()

24
+---+------+------+
|age|gender|course|
+---+------+------+
| 28|Female|    DB|
| 28|Female|   MVC|
| 29|  Male|    PF|
| 28|Female|   OOP|
| 29|Female| Cloud|
| 29|  Male| Cloud|
| 29|Female|   DSA|
| 29|  Male|   OOP|
| 29|  Male|    DB|
| 28|Female|    PF|
| 29|Female|   MVC|
| 29|Female|    DB|
| 28|  Male|    PF|
| 28|Female| Cloud|
| 29|  Male|   MVC|
| 28|  Male|   OOP|
| 28|  Male|   DSA|
| 29|Female|    PF|
| 28|  Male|   MVC|
| 28|  Male|    DB|
+---+------+------+
only showing top 20 rows

# Spark DF (sort, orderBy)

In [0]:
df.show()

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

In [0]:
df.sort(df.marks, 'age').show()

+---+------+-----------------+------+-------+-----+--------------------+
|age|gender|             name|course|   roll|marks|               email|
+---+------+-----------------+------+-------+-----+--------------------+
| 28|  Male|  Marylee Capasso|   DSA|2081560|   20|Sheryll Towler_Do...|
| 28|Female|   Maybell Duguay| Cloud| 261439|   20|Nicole Harwood_Ju...|
| 28|Female|     Jc Andrepont|    PF| 972733|   20|Eda Neathery_Eda ...|
| 29|Female|   Tamera Blakley|   DSA|3911247|   20|Donna Yerby_Bonit...|
| 29|  Male|   Jalisa Swenson|   OOP|4751515|   20|Annika Hoffman_Hu...|
| 29|Female|  Gonzalo Ferebee|   DSA|5631172|   20|Jeannetta Golden_...|
| 29|  Male|Michelle Ruggiero|    PF|6001585|   20|Paris Hutton_Marg...|
| 29|Female|Michelle Ruggiero|    DB|9232210|   20|Donna Yerby_Latia...|
| 29|  Male|     Elenore Choy|    DB|3652057|   20|Jc Andrepont_Gonz...|
| 28|  Male|      Abram Nagao| Cloud|2652463|   21|Eda Neathery_Anni...|
| 28|  Male|   Bonita Higuera| Cloud|7671835|   21|Taryn Brownlee_Se...|
| 28|Female|  Sebrina Maresca|    PF|5742239|   21|Bonita Higuera_Se...|
| 28|  Male|    Kizzy Brenner| Cloud|4622328|   21|Leontine Phillips...|
| 28|  Male|      Billi Clore|    DB|9151306|   21|Latia Vanhoose_Er...|
| 29|  Male|  Sebrina Maresca| Cloud|5042394|   21|Donna Yerby_Miche...|
| 29|Female|  Gonzalo Ferebee|   OOP|2262603|   21|Bonita Higuera_Ch...|
| 29|  Male|   Tamera Blakley|   OOP|7341268|   21|Anna Santos_Naoma...|
| 29|Female|   Alberta Freund|   OOP|4501424|   21|Toshiko Hillyard_...|
| 29|Female|   Nicole Harwood|    PF|8121198|   21|Bonita Higuera_Pr...|
| 28|Female|     Cheri Kenney| Cloud|2281771|   22|Tamera Blakley_Ab...|
+---+------+-----------------+------+-------+-----+--------------------+
only showing top 20 rows

In [0]:
# both sort() and orderBy() does the same thind
df.orderBy(col('marks'), df[0]).show()

+---+------+-----------------+------+-------+-----+--------------------+
|age|gender|             name|course|   roll|marks|               email|
+---+------+-----------------+------+-------+-----+--------------------+
| 28|  Male|  Marylee Capasso|   DSA|2081560|   20|Sheryll Towler_Do...|
| 28|Female|   Maybell Duguay| Cloud| 261439|   20|Nicole Harwood_Ju...|
| 28|Female|     Jc Andrepont|    PF| 972733|   20|Eda Neathery_Eda ...|
| 29|Female|   Tamera Blakley|   DSA|3911247|   20|Donna Yerby_Bonit...|
| 29|  Male|   Jalisa Swenson|   OOP|4751515|   20|Annika Hoffman_Hu...|
| 29|Female|  Gonzalo Ferebee|   DSA|5631172|   20|Jeannetta Golden_...|
| 29|  Male|Michelle Ruggiero|    PF|6001585|   20|Paris Hutton_Marg...|
| 29|Female|Michelle Ruggiero|    DB|9232210|   20|Donna Yerby_Latia...|
| 29|  Male|     Elenore Choy|    DB|3652057|   20|Jc Andrepont_Gonz...|
| 28|  Male|      Abram Nagao| Cloud|2652463|   21|Eda Neathery_Anni...|
| 28|  Male|   Bonita Higuera| Cloud|7671835|   21|Taryn Brownlee_Se...|
| 28|Female|  Sebrina Maresca|    PF|5742239|   21|Bonita Higuera_Se...|
| 28|  Male|    Kizzy Brenner| Cloud|4622328|   21|Leontine Phillips...|
| 28|  Male|      Billi Clore|    DB|9151306|   21|Latia Vanhoose_Er...|
| 29|  Male|  Sebrina Maresca| Cloud|5042394|   21|Donna Yerby_Miche...|
| 29|Female|  Gonzalo Ferebee|   OOP|2262603|   21|Bonita Higuera_Ch...|
| 29|  Male|   Tamera Blakley|   OOP|7341268|   21|Anna Santos_Naoma...|
| 29|Female|   Alberta Freund|   OOP|4501424|   21|Toshiko Hillyard_...|
| 29|Female|   Nicole Harwood|    PF|8121198|   21|Bonita Higuera_Pr...|
| 28|Female|     Cheri Kenney| Cloud|2281771|   22|Tamera Blakley_Ab...|
+---+------+-----------------+------+-------+-----+--------------------+
only showing top 20 rows

In [0]:
df.sort(df.marks.asc(), df.age.desc()).show() # sorting in assencing and descending order

+---+------+-----------------+------+-------+-----+--------------------+
|age|gender|             name|course|   roll|marks|               email|
+---+------+-----------------+------+-------+-----+--------------------+
| 29|Female|Michelle Ruggiero|    DB|9232210|   20|Donna Yerby_Latia...|
| 29|  Male|     Elenore Choy|    DB|3652057|   20|Jc Andrepont_Gonz...|
| 29|  Male|   Jalisa Swenson|   OOP|4751515|   20|Annika Hoffman_Hu...|
| 29|Female|  Gonzalo Ferebee|   DSA|5631172|   20|Jeannetta Golden_...|
| 29|Female|   Tamera Blakley|   DSA|3911247|   20|Donna Yerby_Bonit...|
| 29|  Male|Michelle Ruggiero|    PF|6001585|   20|Paris Hutton_Marg...|
| 28|Female|   Maybell Duguay| Cloud| 261439|   20|Nicole Harwood_Ju...|
| 28|  Male|  Marylee Capasso|   DSA|2081560|   20|Sheryll Towler_Do...|
| 28|Female|     Jc Andrepont|    PF| 972733|   20|Eda Neathery_Eda ...|
| 29|  Male|  Sebrina Maresca| Cloud|5042394|   21|Donna Yerby_Miche...|
| 29|Female|   Nicole Harwood|    PF|8121198|   21|Bonita Higuera_Pr...|
| 29|  Male|   Tamera Blakley|   OOP|7341268|   21|Anna Santos_Naoma...|
| 29|Female|   Alberta Freund|   OOP|4501424|   21|Toshiko Hillyard_...|
| 29|Female|  Gonzalo Ferebee|   OOP|2262603|   21|Bonita Higuera_Ch...|
| 28|  Male|    Kizzy Brenner| Cloud|4622328|   21|Leontine Phillips...|
| 28|  Male|   Bonita Higuera| Cloud|7671835|   21|Taryn Brownlee_Se...|
| 28|  Male|      Abram Nagao| Cloud|2652463|   21|Eda Neathery_Anni...|
| 28|Female|  Sebrina Maresca|    PF|5742239|   21|Bonita Higuera_Se...|
| 28|  Male|      Billi Clore|    DB|9151306|   21|Latia Vanhoose_Er...|
| 29|Female|   Maybell Duguay|   MVC|1102536|   22|Somer Stoecker_Ma...|
+---+------+-----------------+------+-------+-----+--------------------+
only showing top 20 rows

In [0]:
df.orderBy(df.marks.asc(), df.age.desc()).show()
# sortind work perfectly on integers but with strings it will not throw any error by it wont work fine

+---+------+-----------------+------+-------+-----+--------------------+
|age|gender|             name|course|   roll|marks|               email|
+---+------+-----------------+------+-------+-----+--------------------+
| 29|Female|Michelle Ruggiero|    DB|9232210|   20|Donna Yerby_Latia...|
| 29|  Male|     Elenore Choy|    DB|3652057|   20|Jc Andrepont_Gonz...|
| 29|  Male|   Jalisa Swenson|   OOP|4751515|   20|Annika Hoffman_Hu...|
| 29|Female|  Gonzalo Ferebee|   DSA|5631172|   20|Jeannetta Golden_...|
| 29|Female|   Tamera Blakley|   DSA|3911247|   20|Donna Yerby_Bonit...|
| 29|  Male|Michelle Ruggiero|    PF|6001585|   20|Paris Hutton_Marg...|
| 28|Female|   Maybell Duguay| Cloud| 261439|   20|Nicole Harwood_Ju...|
| 28|  Male|  Marylee Capasso|   DSA|2081560|   20|Sheryll Towler_Do...|
| 28|Female|     Jc Andrepont|    PF| 972733|   20|Eda Neathery_Eda ...|
| 29|  Male|  Sebrina Maresca| Cloud|5042394|   21|Donna Yerby_Miche...|
| 29|Female|   Nicole Harwood|    PF|8121198|   21|Bonita Higuera_Pr...|
| 29|  Male|   Tamera Blakley|   OOP|7341268|   21|Anna Santos_Naoma...|
| 29|Female|   Alberta Freund|   OOP|4501424|   21|Toshiko Hillyard_...|
| 29|Female|  Gonzalo Ferebee|   OOP|2262603|   21|Bonita Higuera_Ch...|
| 28|  Male|    Kizzy Brenner| Cloud|4622328|   21|Leontine Phillips...|
| 28|  Male|   Bonita Higuera| Cloud|7671835|   21|Taryn Brownlee_Se...|
| 28|  Male|      Abram Nagao| Cloud|2652463|   21|Eda Neathery_Anni...|
| 28|Female|  Sebrina Maresca|    PF|5742239|   21|Bonita Higuera_Se...|
| 28|  Male|      Billi Clore|    DB|9151306|   21|Latia Vanhoose_Er...|
| 29|Female|   Maybell Duguay|   MVC|1102536|   22|Somer Stoecker_Ma...|
+---+------+-----------------+------+-------+-----+--------------------+
only showing top 20 rows

# Quiz (sort, orderBy)

In [0]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName('sork quiz').getOrCreate()
df = spark.read.options(header='True', inferschema='True').csv('/FileStore/tables/OfficeData.csv')
df.show()

+-------------+----------+-----+------+---+-----+
|employee_name|department|state|salary|age|bonus|
+-------------+----------+-----+------+---+-----+
|        James|     Sales|   NY| 90000| 34|10000|
|      Michael|     Sales|   NY| 86000| 56|20000|
|       Robert|     Sales|   CA| 81000| 30|23000|
|        Maria|   Finance|   CA| 90000| 24|23000|
|        Raman|   Finance|   CA| 99000| 40|24000|
|        Scott|   Finance|   NY| 83000| 36|19000|
|          Jen|   Finance|   NY| 79000| 53|15000|
|         Jeff| Marketing|   CA| 80000| 25|18000|
|        Kumar| Marketing|   NY| 91000| 50|21000|
+-------------+----------+-----+------+---+-----+

In [0]:
df.sort(df.bonus).show()

+-------------+----------+-----+------+---+-----+
|employee_name|department|state|salary|age|bonus|
+-------------+----------+-----+------+---+-----+
|        James|     Sales|   NY| 90000| 34|10000|
|          Jen|   Finance|   NY| 79000| 53|15000|
|         Jeff| Marketing|   CA| 80000| 25|18000|
|        Scott|   Finance|   NY| 83000| 36|19000|
|      Michael|     Sales|   NY| 86000| 56|20000|
|        Kumar| Marketing|   NY| 91000| 50|21000|
|       Robert|     Sales|   CA| 81000| 30|23000|
|        Maria|   Finance|   CA| 90000| 24|23000|
|        Raman|   Finance|   CA| 99000| 40|24000|
+-------------+----------+-----+------+---+-----+

In [0]:
df.sort(df.age.desc(), df.salary.asc()).show()

+-------------+----------+-----+------+---+-----+
|employee_name|department|state|salary|age|bonus|
+-------------+----------+-----+------+---+-----+
|      Michael|     Sales|   NY| 86000| 56|20000|
|          Jen|   Finance|   NY| 79000| 53|15000|
|        Kumar| Marketing|   NY| 91000| 50|21000|
|        Raman|   Finance|   CA| 99000| 40|24000|
|        Scott|   Finance|   NY| 83000| 36|19000|
|        James|     Sales|   NY| 90000| 34|10000|
|       Robert|     Sales|   CA| 81000| 30|23000|
|         Jeff| Marketing|   CA| 80000| 25|18000|
|        Maria|   Finance|   CA| 90000| 24|23000|
+-------------+----------+-----+------+---+-----+

In [0]:
df.sort(df.age.desc(), df.bonus.desc(), df.salary.asc()).show()

+-------------+----------+-----+------+---+-----+
|employee_name|department|state|salary|age|bonus|
+-------------+----------+-----+------+---+-----+
|      Michael|     Sales|   NY| 86000| 56|20000|
|          Jen|   Finance|   NY| 79000| 53|15000|
|        Kumar| Marketing|   NY| 91000| 50|21000|
|        Raman|   Finance|   CA| 99000| 40|24000|
|        Scott|   Finance|   NY| 83000| 36|19000|
|        James|     Sales|   NY| 90000| 34|10000|
|       Robert|     Sales|   CA| 81000| 30|23000|
|         Jeff| Marketing|   CA| 80000| 25|18000|
|        Maria|   Finance|   CA| 90000| 24|23000|
+-------------+----------+-----+------+---+-----+

# Spark DF (Group By)

In [0]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName('Distinct and Duplicate').getOrCreate()
df = spark.read.options(header='True', inferschema='True').csv('/FileStore/tables/StudentData.csv')
df.show()

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

In [0]:
# while working with groutBy() we cant directly see data using show(). We must perform some aggrigation(summing the column/product of the column/min value of that group/... ) to see output
df.groupBy('gender').show()

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<command-570313305499405> in <module>
      1 # while working with groutBy() we cant directly see data using show(). We must perform some aggrigation(summing the column/product of the column/min value of that group/... ) to see output
----> 2 df.groupBy('gender').show()

AttributeError: 'GroupedData' object has no attribute 'show'

In [0]:
df.groupBy('gender').sum('marks').show()

+------+----------+
|gender|sum(marks)|
+------+----------+
|Female|     29636|
|  Male|     30461|
+------+----------+

In [0]:
df.groupBy('gender').min('marks').show()

+------+----------+
|gender|min(marks)|
+------+----------+
|Female|        20|
|  Male|        20|
+------+----------+

In [0]:
df.groupBy('gender').max('marks').show()

+------+----------+
|gender|max(marks)|
+------+----------+
|Female|        99|
|  Male|        99|
+------+----------+

In [0]:
df.groupBy('course').count().show()

+------+-----+
|course|count|
+------+-----+
|    PF|  166|
|    DB|  157|
|   MVC|  157|
|   DSA|  176|
| Cloud|  192|
|   OOP|  152|
+------+-----+

In [0]:
df.groupBy(df.age).avg('marks').show()
df.groupBy(df.age).mean('marks').show()

+---+------------------+
|age|        avg(marks)|
+---+------------------+
| 28|60.487854251012145|
| 29|59.715415019762844|
+---+------------------+

+---+------------------+
|age|        avg(marks)|
+---+------------------+
| 28|60.487854251012145|
| 29|59.715415019762844|
+---+------------------+

# Spark DF(Group By - Multiple Columns and Aggregations)

In [0]:
df.groupBy(df.course, df.age).count().show()

+------+---+-----+
|course|age|count|
+------+---+-----+
|   MVC| 28|   72|
|   MVC| 29|   85|
| Cloud| 28|  100|
|    PF| 29|   87|
|    PF| 28|   79|
|   OOP| 29|   74|
|   DSA| 28|   83|
| Cloud| 29|   92|
|    DB| 28|   82|
|   DSA| 29|   93|
|   OOP| 28|   78|
|    DB| 29|   75|
+------+---+-----+

In [0]:
df.groupBy(df.course, df.age).count().sum().show()

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<command-570313305499414> in <module>
----> 1 df.groupBy(df.course, df.age).count().sum().show()

/databricks/spark/python/pyspark/sql/dataframe.py in __getattr__(self, name)
   1798         """
   1799         if name not in self.columns:
-> 1800             raise AttributeError(
   1801                 "'%s' object has no attribute '%s'" % (self.__class__.__name__, name))
   1802         jc = self._jdf.apply(name)

AttributeError: 'DataFrame' object has no attribute 'sum'

In [0]:
# for performing multiple aggregations we need to import aggrigate functions first
from pyspark.sql.functions import sum, min, max, mean, count, avg

df.groupBy(df.course).agg(count(df.marks).alias('count'),sum(df.marks).alias('sum'),avg(df.marks).alias('avg')).show()

+------+-----+-----+------------------+
|course|count|  sum|               avg|
+------+-----+-----+------------------+
|    PF|  166| 9933| 59.83734939759036|
|    DB|  157| 9270|59.044585987261144|
|   MVC|  157| 9585| 61.05095541401274|
|   DSA|  176|10950| 62.21590909090909|
| Cloud|  192|11443|59.598958333333336|
|   OOP|  152| 8916|  58.6578947368421|
+------+-----+-----+------------------+

# Group By - Filtering

In [0]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import min, max, avg, sum, count, mean
spark = SparkSession.builder.appName('Filtering').getOrCreate()

df = spark.read.options(header='True', inferschema='True').csv('/FileStore/tables/StudentData.csv')
df.printSchema()
df.show()

root
 |-- age: integer (nullable = true)
 |-- gender: string (nullable = true)
 |-- name: string (nullable = true)
 |-- course: string (nullable = true)
 |-- roll: integer (nullable = true)
 |-- marks: integer (nullable = true)
 |-- email: string (nullable = true)

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

In [0]:
df1 = df.filter(df.gender == 'Male').groupBy('course', 'gender').agg(count('*').alias('total_count'))
df1.show()

+------+------+-----------+
|course|gender|total_count|
+------+------+-----------+
|   OOP|  Male|         70|
|    DB|  Male|         82|
|   MVC|  Male|         86|
|    PF|  Male|         97|
| Cloud|  Male|         86|
|   DSA|  Male|         78|
+------+------+-----------+

In [0]:
# method 1
df1.where(df1.total_count > 85).show() # as we are adding new alias name we need to assign it to DF and apply where()
df1.filter(df1.total_count > 85).show()

+------+------+-----------+
|course|gender|total_count|
+------+------+-----------+
|   MVC|  Male|         86|
|    PF|  Male|         97|
| Cloud|  Male|         86|
+------+------+-----------+

+------+------+-----------+
|course|gender|total_count|
+------+------+-----------+
|   MVC|  Male|         86|
|    PF|  Male|         97|
| Cloud|  Male|         86|
+------+------+-----------+

In [0]:
# method 2, using column reference. That means col() is not actually depend on DF it is dependent on context

df.filter(df.gender == 'Male').groupBy('course', 'gender').agg(count('*').alias('total_count')).where(col('total_count') > 85).show()

+------+------+-----------+
|course|gender|total_count|
+------+------+-----------+
|   MVC|  Male|         86|
|    PF|  Male|         97|
| Cloud|  Male|         86|
+------+------+-----------+

# Quiz (Group By)

In [0]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lit, avg, min, max, count, mean, sum

spark = SparkSession.builder.appName('GroupBy').getOrCreate()
df = spark.read.options(header='True', inferschema='True').csv('/FileStore/tables/StudentData.csv')

In [0]:
df.groupBy(df.course).agg(count('*').alias('total_count')).show()

+------+-----------+
|course|total_count|
+------+-----------+
|    PF|        166|
|    DB|        157|
|   MVC|        157|
|   DSA|        176|
| Cloud|        192|
|   OOP|        152|
+------+-----------+

In [0]:
df.groupBy(df.gender, df.course).agg(count('*').alias('total_count')).show()

+------+------+-----------+
|gender|course|total_count|
+------+------+-----------+
|Female| Cloud|        106|
|Female|   OOP|         82|
|  Male|    PF|         97|
|  Male|    DB|         82|
|  Male| Cloud|         86|
|  Male|   OOP|         70|
|Female|   DSA|         98|
|Female|    DB|         75|
|  Male|   DSA|         78|
|  Male|   MVC|         86|
|Female|   MVC|         71|
|Female|    PF|         69|
+------+------+-----------+

In [0]:
df.groupBy(df.gender, df.course).agg(sum(df.marks).alias('total_marks')).show()

+------+------+-----------+
|gender|course|total_marks|
+------+------+-----------+
|Female| Cloud|       6316|
|Female|   OOP|       4682|
|  Male|    PF|       5960|
|  Male|    DB|       5073|
|  Male| Cloud|       5127|
|  Male|   OOP|       4234|
|Female|   DSA|       6124|
|Female|    DB|       4197|
|  Male|   DSA|       4826|
|  Male|   MVC|       5241|
|Female|   MVC|       4344|
|Female|    PF|       3973|
+------+------+-----------+

In [0]:
df.groupBy(df.age, df.course).agg(min(df.marks).alias('min_marks'), max(df.marks).alias('max_marks'), avg(df.marks).alias('avg_marks')).show()

+---+------+---------+---------+------------------+
|age|course|min_marks|max_marks|         avg_marks|
+---+------+---------+---------+------------------+
| 29|   OOP|       20|       99|59.729729729729726|
| 28|    PF|       20|       98| 63.75949367088607|
| 28|    DB|       21|       98| 58.76829268292683|
| 28|   DSA|       20|       99|  64.6867469879518|
| 29|    DB|       20|       98|59.346666666666664|
| 28| Cloud|       20|       99|             58.08|
| 29|   DSA|       20|       99| 60.01075268817204|
| 28|   MVC|       23|       99| 60.44444444444444|
| 28|   OOP|       23|       99| 57.64102564102564|
| 29|    PF|       20|       99|56.275862068965516|
| 29|   MVC|       22|       99| 61.56470588235294|
| 29| Cloud|       21|       98|             61.25|
+---+------+---------+---------+------------------+

# Quiz (Word Count)

In [0]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lit, avg, min, max, count, mean, sum

spark = SparkSession.builder.appName('GroupBy').getOrCreate()
df = spark.read.text('/FileStore/tables/WordData.txt')
df.show()

+------+
| value|
+------+
| Apple|
|   Mic|
|   Mic|
| Apple|
|Laptop|
| Apple|
|   Mic|
|   Mic|
| Apple|
|Laptop|
| Chair|
| Chair|
| Chair|
|   Bag|
|Mobile|
|  Book|
| Chair|
| Chair|
| Chair|
|   Bag|
+------+
only showing top 20 rows

In [0]:
df.groupBy('value').count().show()

+------+-----+
| value|count|
+------+-----+
|   Mic|   10|
| Chair|   15|
|  Book|    5|
|Laptop|    5|
|   Bag|    5|
|Mobile|    5|
| Apple|   10|
+------+-----+

# Spark DF (UDFs)

In [0]:
# UDF- User Derined Function

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lit, udf
from pyspark.sql.types import IntegerType

spark = SparkSession.builder.appName('UDF').getOrCreate()
df = spark.read.options(header='True', inferschema='True').csv('/FileStore/tables/OfficeData.csv')

df.printSchema()
df.show()

root
 |-- employee_name: string (nullable = true)
 |-- department: string (nullable = true)
 |-- state: string (nullable = true)
 |-- salary: integer (nullable = true)
 |-- age: integer (nullable = true)
 |-- bonus: integer (nullable = true)

+-------------+----------+-----+------+---+-----+
|employee_name|department|state|salary|age|bonus|
+-------------+----------+-----+------+---+-----+
|        James|     Sales|   NY| 90000| 34|10000|
|      Michael|     Sales|   NY| 86000| 56|20000|
|       Robert|     Sales|   CA| 81000| 30|23000|
|        Maria|   Finance|   CA| 90000| 24|23000|
|        Raman|   Finance|   CA| 99000| 40|24000|
|        Scott|   Finance|   NY| 83000| 36|19000|
|          Jen|   Finance|   NY| 79000| 53|15000|
|         Jeff| Marketing|   CA| 80000| 25|18000|
|        Kumar| Marketing|   NY| 91000| 50|21000|
+-------------+----------+-----+------+---+-----+

In [0]:
def get_total_salary(salary, bonus):
    return salary + bonus

# registering the function to udf
totalSalaryUDF = udf(lambda x, y: get_total_salary(x, y), IntegerType())# by default udf functions will return string tipe so we need to explecetly mention data types

df.withColumn('total_salary', totalSalaryUDF(df.salary, df.bonus)).show()

+-------------+----------+-----+------+---+-----+------------+
|employee_name|department|state|salary|age|bonus|total_salary|
+-------------+----------+-----+------+---+-----+------------+
|        James|     Sales|   NY| 90000| 34|10000|      100000|
|      Michael|     Sales|   NY| 86000| 56|20000|      106000|
|       Robert|     Sales|   CA| 81000| 30|23000|      104000|
|        Maria|   Finance|   CA| 90000| 24|23000|      113000|
|        Raman|   Finance|   CA| 99000| 40|24000|      123000|
|        Scott|   Finance|   NY| 83000| 36|19000|      102000|
|          Jen|   Finance|   NY| 79000| 53|15000|       94000|
|         Jeff| Marketing|   CA| 80000| 25|18000|       98000|
|        Kumar| Marketing|   NY| 91000| 50|21000|      112000|
+-------------+----------+-----+------+---+-----+------------+

# Quiz (UDFs)

In [0]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import udf
from pyspark.sql.types import DoubleType

In [0]:
spark = SparkSession.builder.appName('UDFs').getOrCreate()
df = spark.read.options(header='True', inferschema='True').csv('/FileStore/tables/OfficeData.csv')

df.printSchema()
df.show()

root
 |-- employee_name: string (nullable = true)
 |-- department: string (nullable = true)
 |-- state: string (nullable = true)
 |-- salary: integer (nullable = true)
 |-- age: integer (nullable = true)
 |-- bonus: integer (nullable = true)

+-------------+----------+-----+------+---+-----+
|employee_name|department|state|salary|age|bonus|
+-------------+----------+-----+------+---+-----+
|        James|     Sales|   NY| 90000| 34|10000|
|      Michael|     Sales|   NY| 86000| 56|20000|
|       Robert|     Sales|   CA| 81000| 30|23000|
|        Maria|   Finance|   CA| 90000| 24|23000|
|        Raman|   Finance|   CA| 99000| 40|24000|
|        Scott|   Finance|   NY| 83000| 36|19000|
|          Jen|   Finance|   NY| 79000| 53|15000|
|         Jeff| Marketing|   CA| 80000| 25|18000|
|        Kumar| Marketing|   NY| 91000| 50|21000|
+-------------+----------+-----+------+---+-----+

In [0]:
# def sal_increment(state, salary, bonus):
#     sal_inc = None
#     bns_inc = None
    
#     if (state == 'NY'):
#         sal_inc = salary * 0.10
#         bns_inc = bonus * 0.05
#     elif (state == 'CA'):
#         sal_inc = salary * 0.12
#         bns_inc = bonus * 0.03
#         return sal_inc + bns_inc

def sal_increment(state, salary, bonus):
    sum = None
    if (state == 'NY'):
        sum = salary * 0.10
        sum += bonus * 0.05
    elif (state == 'CA'):
        sum = salary * 0.12
        sum += bonus * 0.03
    return sum

incrementUDF = udf(lambda x, y, z: sal_increment(x, y, z), DoubleType())

df.withColumn('increment', incrementUDF(df.state, df.salary, df.bonus)).show()

+-------------+----------+-----+------+---+-----+---------+
|employee_name|department|state|salary|age|bonus|increment|
+-------------+----------+-----+------+---+-----+---------+
|        James|     Sales|   NY| 90000| 34|10000|   9500.0|
|      Michael|     Sales|   NY| 86000| 56|20000|   9600.0|
|       Robert|     Sales|   CA| 81000| 30|23000|  10410.0|
|        Maria|   Finance|   CA| 90000| 24|23000|  11490.0|
|        Raman|   Finance|   CA| 99000| 40|24000|  12600.0|
|        Scott|   Finance|   NY| 83000| 36|19000|   9250.0|
|          Jen|   Finance|   NY| 79000| 53|15000|   8650.0|
|         Jeff| Marketing|   CA| 80000| 25|18000|  10140.0|
|        Kumar| Marketing|   NY| 91000| 50|21000|  10150.0|
+-------------+----------+-----+------+---+-----+---------+

# Cache and Persist work flow

Cache under the hood use the Precist function.

Cache and Persist are actually used to save the data in the memory at any given point, so that whenever there are any further action or transformations beyond the point of cache it will not refer back to the transformation again it will start flowing the data from the cache point.

In [0]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lit, avg, min, max, count, mean, sum

spark = SparkSession.builder.appName('Cache').getOrCreate()
df = spark.read.options(header='True', inferschema='True').csv('/FileStore/tables/StudentData.csv')
df.show()

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

In [0]:
df = df.groupBy('course', 'gender', 'age').count()

In [0]:
df = df.withColumn('dummy', col('age') * 100)

In [0]:
df.show()

+------+------+---+-----+-----+
|course|gender|age|count|dummy|
+------+------+---+-----+-----+
| Cloud|Female| 29|   49| 2900|
|   DSA|Female| 28|   47| 2800|
|    PF|Female| 29|   34| 2900|
|   OOP|Female| 29|   39| 2900|
|   DSA|Female| 29|   51| 2900|
|    PF|Female| 28|   35| 2800|
|   MVC|Female| 28|   34| 2800|
|    DB|  Male| 28|   42| 2800|
|   OOP|  Male| 29|   35| 2900|
|   MVC|  Male| 29|   48| 2900|
|   MVC|Female| 29|   37| 2900|
|    DB|Female| 29|   35| 2900|
|   OOP|Female| 28|   43| 2800|
| Cloud|Female| 28|   57| 2800|
| Cloud|  Male| 29|   43| 2900|
|    PF|  Male| 28|   44| 2800|
|   DSA|  Male| 28|   36| 2800|
|    DB|Female| 28|   40| 2800|
|    DB|  Male| 29|   40| 2900|
|    PF|  Male| 29|   53| 2900|
+------+------+---+-----+-----+
only showing top 20 rows

In [0]:
#it will capture all the data from above action
df.cache()

Out[35]: DataFrame[course: string, gender: string, age: int, count: bigint, dummy: int]

In [0]:
# here again it will not perform all transformations we will get the data from cache()

print(df.count())
df.show()

24
+------+------+---+-----+-----+
|course|gender|age|count|dummy|
+------+------+---+-----+-----+
| Cloud|Female| 29|   49| 2900|
|   DSA|Female| 28|   47| 2800|
|    PF|Female| 29|   34| 2900|
|   OOP|Female| 29|   39| 2900|
|   DSA|Female| 29|   51| 2900|
|    PF|Female| 28|   35| 2800|
|   MVC|Female| 28|   34| 2800|
|    DB|  Male| 28|   42| 2800|
|   OOP|  Male| 29|   35| 2900|
|   MVC|  Male| 29|   48| 2900|
|   MVC|Female| 29|   37| 2900|
|    DB|Female| 29|   35| 2900|
|   OOP|Female| 28|   43| 2800|
| Cloud|Female| 28|   57| 2800|
| Cloud|  Male| 29|   43| 2900|
|    PF|  Male| 28|   44| 2800|
|   DSA|  Male| 28|   36| 2800|
|    DB|Female| 28|   40| 2800|
|    DB|  Male| 29|   40| 2900|
|    PF|  Male| 29|   53| 2900|
+------+------+---+-----+-----+
only showing top 20 rows

# Spark DF (DF to RDD)

DF are nearly a wrapper on the RDD. Underline all the transformation and procss done under the DF is RDD

In [0]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('DF to RDD').getOrCreate()
df = spark.read.options(header='True',inferschema='True').csv('/FileStore/tables/StudentData.csv')
df.show()

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

In [0]:
type(df)

Out[39]: pyspark.sql.dataframe.DataFrame

In [0]:
rdd = df.rdd

type(rdd)

Out[40]: pyspark.rdd.RDD

In [0]:
# DF stores data in structured manner thats why after converting DF to RDD we will get key value pairs
rdd.collect()

Out[43]: [Row(age=28, gender='Female', name='Hubert Oliveras', course='DB', roll=2984, marks=59, email='Annika Hoffman_Naoma Fritts@OOP.com'),
 Row(age=29, gender='Female', name='Toshiko Hillyard', course='Cloud', roll=12899, marks=62, email='Margene Moores_Marylee Capasso@DB.com'),
 Row(age=28, gender='Male', name='Celeste Lollis', course='PF', roll=21267, marks=45, email='Jeannetta Golden_Jenna Montague@DSA.com'),
 Row(age=29, gender='Female', name='Elenore Choy', course='DB', roll=32877, marks=29, email='Billi Clore_Mitzi Seldon@DB.com'),
 Row(age=28, gender='Male', name='Sheryll Towler', course='DSA', roll=41487, marks=41, email='Claude Panos_Judie Chipps@OOP.com'),
 Row(age=28, gender='Male', name='Margene Moores', course='MVC', roll=52771, marks=32, email='Toshiko Hillyard_Clementina Menke@MVC.com'),
 Row(age=28, gender='Male', name='Neda Briski', course='OOP', roll=61973, marks=69, email='Alberta Freund_Elenore Choy@DB.com'),
 Row(age=28, gender='Female', name='Claude Panos', course='Cloud', roll=72409, marks=85, email='Sheryll Towler_Alberta Freund@Cloud.com'),
 Row(age=28, gender='Male', name='Celeste Lollis', course='MVC', roll=81492, marks=64, email='Nicole Harwood_Claude Panos@MVC.com'),
 Row(age=29, gender='Male', name='Cordie Harnois', course='OOP', roll=92882, marks=51, email='Judie Chipps_Clementina Menke@MVC.com'),
 Row(age=29, gender='Female', name='Kena Wild', course='DSA', roll=102285, marks=35, email='Dustin Feagins_Margene Moores@OOP.com'),
 Row(age=29, gender='Male', name='Ernest Rossbach', course='DB', roll=111449, marks=53, email='Maybell Duguay_Abram Nagao@OOP.com'),
 Row(age=28, gender='Female', name='Latia Vanhoose', course='DB', roll=122502, marks=27, email='Latia Vanhoose_Mitzi Seldon@OOP.com'),
 Row(age=29, gender='Female', name='Latia Vanhoose', course='MVC', roll=132110, marks=55, email='Eda Neathery_Nicole Harwood@Cloud.com'),
 Row(age=29, gender='Male', name='Neda Briski', course='PF', roll=141770, marks=42, email='Margene Moores_Michelle Ruggiero@MVC.com'),
 Row(age=29, gender='Female', name='Latia Vanhoose', course='DB', roll=152159, marks=27, email='Claude Panos_Santa Kerfien@DB.com'),
 Row(age=29, gender='Male', name='Loris Crossett', course='MVC', roll=161771, marks=36, email='Mitzi Seldon_Jenna Montague@MVC.com'),
 Row(age=29, gender='Male', name='Annika Hoffman', course='OOP', roll=171660, marks=22, email='Taryn Brownlee_Mitzi Seldon@MVC.com'),
 Row(age=29, gender='Male', name='Santa Kerfien', course='PF', roll=182129, marks=56, email='Judie Chipps_Taryn Brownlee@Cloud.com'),
 Row(age=28, gender='Female', name='Mickey Cortright', course='DB', roll=192537, marks=62, email='Ernest Rossbach_Marylee Capasso@Cloud.com'),
 Row(age=29, gender='Female', name='Loris Crossett', course='PF', roll=201487, marks=96, email='Elenore Choy_Latia Vanhoose@Cloud.com'),
 Row(age=29, gender='Female', name='Niki Klimek', course='PF', roll=211508, marks=23, email='Cordie Harnois_Judie Chipps@PF.com'),
 Row(age=28, gender='Female', name='Kena Wild', course='Cloud', roll=221750, marks=60, email='Mitzi Seldon_Jenna Montague@DSA.com'),
 Row(age=28, gender='Female', name='Jc Andrepont', course='DSA', roll=232060, marks=58, email='Billi Clore_Abram Nagao@MVC.com'),
 Row(age=29, gender='Female', name='Anna Santos', course='Cloud', roll=242254, marks=68, email='Jc Andrepont_Hubert Oliveras@Cloud.com'),
 Row(age=28, gender='Female', name='Alberta Freund', course='OOP', roll=251805, marks=83, email='Annika Hoffman_Sheryll Towler@MVC.com'),
 Row(age=28, gender='Female', name='Maybell Duguay', course='Cloud', roll=261439, marks=20, email='Nicole Harwood_Judie Chipps@DB.com'),
 Row(age=29, gender='Female', name='Paris Hutton', course='DSA', roll=271472, marks=99, email='Sheryll Towler_Alberta Freund@DSA.com'),
 Row(age=29, gender='Female', name='Cheri Kenney', course='Cloud', roll=281408, marks=43, email='Annika Hoffman_Melani Engberg@Cloud.com'),
 Row(age=28, gender='Female', name='Dustin Feagins', course='DSA', roll=291984, marks=82, email='Abram Nagao_Kena Wild@Cloud.com'),
 Row(age=29, gender='Female', name='Claude Panos', course='Cloud', roll=302130, marks=59, email='Sheryll Towler_Leontine Phillips@PF.com'),
 Row(age=28, gender='Female', name='Anna Santos', course='DB', roll=311589, marks=79, email='Celeste Lollis_Mickey Cortright@DSA.com'),
 Row(age=28, gender='Female', name='Cheri Kenney', course='MVC', roll=321816, marks=24, email='Kena Wild_Michelle Ruggiero@DB.com'),
 Row(age=28, gender='Female', name='Loris Crossett', course='PF', roll=332739, marks=62, email='Michelle Ruggiero_Clementina Menke@DB.com'),
 Row(age=28, gender='Female', name='Mickey Cortright', course='DSA', roll=342003, marks=44, email='Mitzi Seldon_Jeannetta Golden@PF.com'),
 Row(age=28, gender='Male', name='Hubert Oliveras', course='OOP', roll=351719, marks=63, email='Lawanda Wohlwend_Abram Nagao@MVC.com'),
 Row(age=28, gender='Male', name='Sebrina Maresca', course='PF', roll=361316, marks=62, email='Nicole Harwood_Latia Vanhoose@DB.com'),
 Row(age=29, gender='Male', name='Jalisa Swenson', course='PF', roll=372873, marks=45, email='Ernest Rossbach_Toshiko Hillyard@DB.com'),
 Row(age=28, gender='Male', name='Kizzy Brenner', course='DB', roll=381712, marks=36, email='Paris Hutton_Kena Wild@MVC.com'),
 Row(age=28, gender='Male', name='Toshiko Hillyard', course='DB', roll=392218, marks=47, email='Leontine Phillips_Billi Clore@MVC.com'),
 Row(age=28, gender='Female', name='Kizzy Brenner', course='Cloud', roll=402409, marks=27, email='Ernest Rossbach_Gonzalo Ferebee@OOP.com'),
 Row(age=29, gender='Female', name='Anna Santos', course='DSA', roll=411479, marks=42, email='Kena Wild_Mitzi Seldon@DB.com'),
 Row(age=28, gender='Male', name='Elenore Choy', course='PF', roll=422704, marks=66, email='Marylee Capasso_Nicole Harwood@MVC.com'),
 Row(age=28, gender='Female', name='Jalisa Swenson', course='OOP', roll=431352, marks=25, email='Gonzalo Ferebee_Judie Chipps@DB.com'),
 Row(age=29, gender='Female', name='Somer Stoecker', course='Cloud', roll=442028, marks=34, email='Taryn Brownlee_Taryn Brownlee@MVC.com'),
 Row(age=28, gender='Female', name='Maybell Duguay', course='DSA', roll=452141, marks=29, email='Leontine Phillips_Elenore Choy@Cloud.com'),
 Row(age=28, gender='Male', name='Dustin Feagins', course='PF', roll=461839, marks=51, email='Neda Briski_Elenore Choy@Cloud.com'),
 Row(age=29, gender='Male', name='Annika Hoffman', course='OOP', roll=472550, marks=35, email='Mitzi Seldon_Abram Nagao@DSA.com'),
 Row(age=29, gender='Male', name='Paris Hutton', course='DB', roll=481229, marks=57, email='Clementina Menke_Paris Hutton@MVC.com'),
 Row(age=29, gender='Female', name='Paris Hutton', course='DSA', roll=492159, marks=60, email='Nicole Harwood_Marylee Capasso@OOP.com'),
 Row(age=29, gender='Female', name='Jenna Montague', course='MVC', roll=502585, marks=43, email='Hubert Oliveras_Jc Andrepont@DSA.com'),
 Row(age=29, gender='Male', name='Billi Clore', course='Cloud', roll=512047, marks=76, email='Taryn Brownlee_Judie Chipps@DSA.com'),
 Row(age=29, gender='Male', name='Toshiko Hillyard', course='OOP', roll=521221, marks=77, email='Hubert Oliveras_Latia Vanhoose@MVC.com'),
 Row(age=28, gender='Male', name='Margene Moores', course='PF', roll=531530, marks=53, email='Cheri Kenney_Melani Engberg@OOP.com'),
 Row(age=29, gender='Female', name='Claude Panos', course='OOP', roll=542821, marks=28, email='Hubert Oliveras_Priscila Tavernier@PF.com'),
 Row(age=28, gender='Female', name='Mickey Cortright', course='DB', roll=551389, marks=43, email='Tijuana Kropf_Jenna Montague@DB.com'),
 Row(age=29, gender='Male', name='Celeste Lollis', course='DSA', roll=562065, marks=85, email='Jc Andrepont_Melani Engberg@OOP.com'),
 Row(age=28, gender='Female', name='Tijuana Kropf', course='PF', roll=571047, marks=41, email='Loris Crossett_Sebrina Maresca@PF.com'),
 Row(age=28, gender='Male', name='Marylee Capasso', course='OOP', roll=581756, marks=52, email='Jeannetta Golden_Loris Crossett@MVC.com'),
 Row(age=29, gender='Male', name='Maybell Duguay', course='DSA', roll=592061, marks=83, email='Eda Neathery_Jenna Montague@Cloud.com'),
 Row(age=28, gender='Female', name='Leontine Phillips', course='DB', roll=602404, marks=48, email='Neda Briski_Cheri Kenney@PF.com'),
 Row(age=28, gender='Female', name='Somer Stoecker', course='Cloud', roll=612490, marks=82, email='Sebrina Maresca_Gonzalo Ferebee@DSA.com'),
 Row(age=28, gender='Male', name='Mitzi Seldon', course='DSA', roll=622981, marks=45, email='Lawanda Wohlwend_Loris Crossett@DSA.com'),
 Row(age=29, gender='Female', name='Judie Chipps', course='Cloud', roll=632793, marks=75, email='Tijuana Kropf_Elenore Choy@PF.com'),
 Row(age=28, gender='Male', name='Priscila Tavernier', course='PF', roll=642594, marks=27, email='Marylee Capasso_Claude Panos@DSA.com'),
 Row(age=29, gender='Male', name='Tamera Blakley', course='MVC', roll=651649, marks=92, email='Latia Vanhoose_Toshiko Hillyard@MVC.com'),
 Row(age=28, gender='Male', name='Sheryll Towler', course='MVC', roll=661079, marks=89, email='Tijuana Kropf_Mickey Cortright@DB.com'),
 Row(age=29, gender='Male', name='Hubert Oliveras', course='MVC', roll=672451, marks=28, email='Annika Hoffman_Mickey Cortright@DSA.com'),
 Row(age=29, gender='Male', name='Sheryll Towler', course='PF', roll=682533, marks=42, email='Billi Clore_Anna Santos@PF.com'),
 Row(age=28, gender='Female', name='Jenna Montague', course='DSA', roll=691564, marks=26, email='Mitzi Seldon_Sebrina Maresca@Cloud.com'),
 Row(age=29, gender='Male', name='Maybell Duguay', course='PF', roll=701486, marks=99, email='Clementina Menke_Latia Vanhoose@Cloud.com'),
 Row(age=29, gender='Male', name='Jenna Montague', course='MVC', roll=711153, marks=45, email='Marylee Capasso_Hubert Oliveras@DB.com'),
 Row(age=28, gender='Male', name='Annika Hoffman', course='Cloud', roll=722193, marks=55, email='Taryn Brownlee_Elenore Choy@DB.com'),
 Row(age=28, gender='Female', name='Celeste Lollis', course='DSA', roll=731879, marks=76, email='Hubert Oliveras_Gonzalo Ferebee@DSA.com'),
 Row(age=29, gender='Male', name='Jeannetta Golden', course='MVC', roll=741875, marks=57, email='Sheryll Towler_Cheri Kenney@DSA.com'),
 Row(age=29, gender='Male', name='Paris Hutton', course='MVC', roll=752504, marks=22, email='Elenore Choy_Elenore Choy@DB.com'),
 Row(age=29, gender='Female', name='Margene Moores', course='MVC', roll=761843, marks=48, email='Ernest Rossbach_Mickey Cortright@DSA.com'),
 Row(age=28, gender='Female', name='Hubert Oliveras', course='DB', roll=771081, marks=79, email='Kizzy Brenner_Dustin Feagins@MVC.com'),
 Row(age=28, gender='Male', name='Alberta Freund', course='PF', roll=781061, marks=75, email='Leontine Phillips_Bonita Higuera@PF.com'),
 Row(age=29, gender='Female', name='Billi Clore', course='OOP', roll=791519, marks=93, email='Elenore Choy_Jalisa Swenson@MVC.com'),
 Row(age=28, gender='Female', name='Billi Clore', course='Cloud', roll=801693, marks=38, email='Niki Klimek_Kizzy Brenner@DB.com'),
 Row(age=29, gender='Female', name='Elenore Choy', course='DB', roll=811824, marks=55, email='Maybell Duguay_Melani Engberg@DB.com'),
 Row(age=28, gender='Male', name='Anna Santos', course='OOP', roll=822396, marks=47, email='Leontine Phillips_Gonzalo Ferebee@Cloud.com'),
 Row(age=28, gender='Male', name='Sheryll Towler', course='DSA', roll=831562, marks=59, email='Kena Wild_Gonzalo Ferebee@Cloud.com'),
 Row(age=29, gender='Male', name='Neda Briski', course='PF', roll=842515, marks=68, email='Neda Briski_Hubert Oliveras@OOP.com'),
 Row(age=28, gender='Female', name='Santa Kerfien', course='Cloud', roll=851620, marks=34, email='Melani Engberg_Sheryll Towler@PF.com'),
 Row(age=29, gender='Female', name='Taryn Brownlee', course='MVC', roll=861849, marks=39, email='Billi Clore_Toshiko Hillyard@MVC.com'),
 Row(age=28, gender='Female', name='Sheryll Towler', course='DSA', roll=871967, marks=64, email='Michelle Ruggiero_Billi Clore@Cloud.com'),
 Row(age=29, gender='Male', name='Clementina Menke', course='DB', roll=882200, marks=76, email='Michelle Ruggiero_Jenna Montague@MVC.com'),
 Row(age=28, gender='Male', name='Margene Moores', course='DSA', roll=892010, marks=93, email='Anna Santos_Naoma Fritts@DSA.com'),
 Row(age=28, gender='Female', name='Somer Stoecker', course='DSA', roll=901958, marks=64, email='Kizzy Brenner_Jc Andrepont@DB.com'),
 Row(age=29, gender='Male', name='Loris Crossett', course='PF', roll=911593, marks=46, email='Gonzalo Ferebee_Mitzi Seldon@PF.com'),
 Row(age=29, gender='Female', name='Sebrina Maresca', course='DB', roll=922210, marks=54, email='Toshiko Hillyard_Santa Kerfien@MVC.com'),
 Row(age=29, gender='Male', name='Naoma Fritts', course='DB', roll=931295, marks=79, email='Hubert Oliveras_Sheryll Towler@DSA.com'),
 Row(age=28, gender='Female', name='Santa Kerfien', course='MVC', roll=941783, marks=94, email='Paris Hutton_Naoma Fritts@DB.com'),
 Row(age=28, gender='Female', name='Lawanda Wohlwend', course='DSA', roll=951686, marks=60, email='Loris Crossett_Nicole Harwood@DSA.com'),
 Row(age=29, gender='Male', name='Abram Nagao', course='MVC', roll=962235, marks=32, email='Jenna Montague_Gonzalo Ferebee@DSA.com'),
 Row(age=28, gender='Female', name='Jc Andrepont', course='PF', roll=972733, marks=20, email='Eda Neathery_Eda Neathery@MVC.com'),
 Row(age=29, gender='Male', name='Niki Klimek', course='PF', roll=982443, marks=94, email='Santa Kerfien_Kizzy Brenner@DB.com'),
 Row(age=28, gender='Female', name='Marylee Capasso', course='OOP', roll=991770, marks=86, email='Margene Moores_Clementina Menke@DB.com'),
 Row(age=28, gender='Male', name='Jenna Montague', course='DSA', roll=1002103, marks=36, email='Melani Engberg_Hubert Oliveras@PF.com'),
 Row(age=29, gender='Female', name='Eda Neathery', course='Cloud', roll=1011971, marks=91, email='Margene Moores_Elenore Choy@MVC.com'),
 Row(age=29, gender='Male', name='Michelle Ruggiero', course='DSA', roll=1022971, marks=99, email='Cordie Harnois_Clementina Menke@OOP.com'),
 Row(age=28, gender='Male', name='Annika Hoffman', course='DB', roll=1031544, marks=44, email='Dustin Feagins_Somer Stoecker@DB.com'),
 Row(age=29, gender='Female', name='Hubert Oliveras', course='DSA', roll=1041483, marks=28, email='Billi Clore_Santa Kerfien@DSA.com'),
 Row(age=28, gender='Male', name='Billi Clore', course='MVC', roll=1052566, marks=78, email='Naoma Fritts_Margene Moores@DSA.com'),
 Row(age=28, gender='Female', name='Nicole Harwood', course='MVC', roll=1061068, marks=82, email='Santa Kerfien_Hubert Oliveras@MVC.com'),
 Row(age=29, gender='Male', name='Clementina Menke', course='PF', roll=1071717, marks=54, email='Celeste Lollis_Leontine Phillips@OOP.com'),
 Row(age=28, gender='Female', name='Claude Panos', course='OOP', roll=1081294, marks=94, email='Kizzy Brenner_Anna Santos@OOP.com'),
 Row(age=29, gender='Male', name='Donna Yerby', course='DSA', roll=1092702, marks=79, email='Marylee Capasso_Alberta Freund@OOP.com'),
 Row(age=29, gender='Female', name='Maybell Duguay', course='MVC', roll=1102536, marks=22, email='Somer Stoecker_Marylee Capasso@OOP.com'),
 Row(age=29, gender='Male', name='Abram Nagao', course='PF', roll=1112161, marks=42, email='Nicole Harwood_Niki Klimek@DB.com'),
 Row(age=28, gender='Female', name='Bonita Higuera', course='DSA', roll=1122348, marks=51, email='Somer Stoecker_Jenna Montague@DB.com'),
 Row(age=29, gender='Female', name='Melani Engberg', course='OOP', roll=1132093, marks=76, email='Kena Wild_Neda Briski@Cloud.com'),
 Row(age=29, gender='Female', name='Marylee Capasso', course='OOP', roll=1142653, marks=61, email='Cordie Harnois_Alberta Freund@DSA.com'),
 Row(age=29, gender='Male', name='Nicole Harwood', course='Cloud', roll=1152571, marks=62, email='Latia Vanhoose_Maybell Duguay@PF.com'),
 Row(age=29, gender='Female', name='Dustin Feagins', course='OOP', roll=1161607, marks=37, email='Eda Neathery_Marylee Capasso@MVC.com'),
 Row(age=28, gender='Female', name='Niki Klimek', course='PF', roll=1172784, marks=24, email='Jeannetta Golden_Abram Nagao@MVC.com'),
 Row(age=29, gender='Female', name='Abram Nagao', course='DSA', roll=1181007, marks=57, email='Anna Santos_Anna Santos@DSA.com'),
 Row(age=28, gender='Male', name='Jalisa Swenson', course='PF', roll=1192555, marks=77, email='Marylee Capasso_Celeste Lollis@Cloud.com'),
 Row(age=29, gender='Female', name='Ernest Rossbach', course='MVC', roll=1201427, marks=80, email='Elenore Choy_Jenna Montague@OOP.com'),
 Row(age=28, gender='Male', name='Nicole Harwood', course='DB', roll=1211495, marks=28, email='Melani Engberg_Jc Andrepont@Cloud.com'),
 Row(age=29, gender='Female', name='Claude Panos', course='DB', roll=1222887, marks=75, email='Hubert Oliveras_Somer Stoecker@Cloud.com'),
 Row(age=28, gender='Female', name='Cordie Harnois', course='OOP', roll=1231943, marks=68, email='Mickey Cortright_Kizzy Brenner@OOP.com'),
 Row(age=28, gender='Male', name='Nicole Harwood', course='OOP', roll=1242426, marks=71, email='Billi Clore_Loris Crossett@Cloud.com'),
 Row(age=28, gender='Male', name='Gonzalo Ferebee', course='Cloud', roll=1251176, marks=60, email='Santa Kerfien_Tamera Blakley@PF.com'),
 Row(age=29, gender='Male', name='Jalisa Swenson', course='Cloud', roll=1261533, marks=70, email='Dustin Feagins_Nicole Harwood@PF.com'),
 Row(age=28, gender='Female', name='Eda Neathery', course='Cloud', roll=1272870, marks=69, email='Somer Stoecker_Dustin Feagins@DB.com'),
 Row(age=28, gender='Female', name='Toshiko Hillyard', course='DSA', roll=1282835, marks=79, email='Somer Stoecker_Toshiko Hillyard@OOP.com'),
 Row(age=28, gender='Male', name='Paris Hutton', course='MVC', roll=1292279, marks=26, email='Paris Hutton_Eda Neathery@DSA.com'),
 Row(age=29, gender='Female', name='Niki Klimek', course='DB', roll=1301784, marks=24, email='Celeste Lollis_Tamera Blakley@DB.com'),
 Row(age=28, gender='Male', name='Bonita Higuera', course='Cloud', roll=1312294, marks=94, email='Eda Neathery_Priscila Tavernier@PF.com'),
 Row(age=28, gender='Female', name='Leontine Phillips', course='MVC', roll=1322629, marks=87, email='Judie Chipps_Michelle Ruggiero@Cloud.com'),
 Row(age=29, gender='Male', name='Jalisa Swenson', course='PF', roll=1332072, marks=88, email='Billi Clore_Kizzy Brenner@Cloud.com'),
 Row(age=28, gender='Male', name='Clementina Menke', course='OOP', roll=1341574, marks=46, email='Elenore Choy_Mickey Cortright@DB.com'),
 Row(age=28, gender='Male', name='Gonzalo Ferebee', course='PF', roll=1352348, marks=95, email='Neda Briski_Somer Stoecker@DB.com'),
 Row(age=29, gender='Female', name='Jalisa Swenson', course='DSA', roll=1362151, marks=51, email='Lawanda Wohlwend_Jenna Montague@PF.com'),
 Row(age=28, gender='Male', name='Lawanda Wohlwend', course='PF', roll=1372552, marks=88, email='Hubert Oliveras_Tijuana Kropf@DSA.com'),
 Row(age=28, gender='Male', name='Abram Nagao', course='DSA', roll=1382959, marks=66, email='Michelle Ruggiero_Kena Wild@OOP.com'),
 Row(age=29, gender='Female', name='Hubert Oliveras', course='Cloud', roll=1392791, marks=94, email='Anna Santos_Alberta Freund@Cloud.com'),
 Row(age=28, gender='Male', name='Bonita Higuera', course='Cloud', roll=1401526, marks=24, email='Jc Andrepont_Cheri Kenney@Cloud.com'),
 Row(age=29, gender='Female', name='Clementina Menke', course='OOP', roll=1412376, marks=65, email='Elenore Choy_Latia Vanhoose@DSA.com'),
 Row(age=29, gender='Female', name='Mickey Cortright', course='Cloud', roll=1421542, marks=71, email='Latia Vanhoose_Kena Wild@OOP.com'),
 Row(age=29, gender='Female', name='Leontine Phillips', course='DB', roll=1432252, marks=67, email='Billi Clore_Sheryll Towler@DB.com'),
 Row(age=28, gender='Female', name='Nicole Harwood', course='PF', roll=1441367, marks=95, email='Jc Andrepont_Anna Santos@DSA.com'),
 Row(age=28, gender='Female', name='Gonzalo Ferebee', course='DB', roll=1451513, marks=69, email='Claude Panos_Tamera Blakley@PF.com'),
 Row(age=29, gender='Female', name='Judie Chipps', course='DB', roll=1461078, marks=31, email='Tijuana Kropf_Billi Clore@OOP.com'),

In [0]:
# rdd.filter(lambda x: x[1] == 'Male').collect()
rdd.filter(lambda x: x['gender'] == 'Male').collect()

Out[44]: [Row(age=28, gender='Male', name='Celeste Lollis', course='PF', roll=21267, marks=45, email='Jeannetta Golden_Jenna Montague@DSA.com'),
 Row(age=28, gender='Male', name='Sheryll Towler', course='DSA', roll=41487, marks=41, email='Claude Panos_Judie Chipps@OOP.com'),
 Row(age=28, gender='Male', name='Margene Moores', course='MVC', roll=52771, marks=32, email='Toshiko Hillyard_Clementina Menke@MVC.com'),
 Row(age=28, gender='Male', name='Neda Briski', course='OOP', roll=61973, marks=69, email='Alberta Freund_Elenore Choy@DB.com'),
 Row(age=28, gender='Male', name='Celeste Lollis', course='MVC', roll=81492, marks=64, email='Nicole Harwood_Claude Panos@MVC.com'),
 Row(age=29, gender='Male', name='Cordie Harnois', course='OOP', roll=92882, marks=51, email='Judie Chipps_Clementina Menke@MVC.com'),
 Row(age=29, gender='Male', name='Ernest Rossbach', course='DB', roll=111449, marks=53, email='Maybell Duguay_Abram Nagao@OOP.com'),
 Row(age=29, gender='Male', name='Neda Briski', course='PF', roll=141770, marks=42, email='Margene Moores_Michelle Ruggiero@MVC.com'),
 Row(age=29, gender='Male', name='Loris Crossett', course='MVC', roll=161771, marks=36, email='Mitzi Seldon_Jenna Montague@MVC.com'),
 Row(age=29, gender='Male', name='Annika Hoffman', course='OOP', roll=171660, marks=22, email='Taryn Brownlee_Mitzi Seldon@MVC.com'),
 Row(age=29, gender='Male', name='Santa Kerfien', course='PF', roll=182129, marks=56, email='Judie Chipps_Taryn Brownlee@Cloud.com'),
 Row(age=28, gender='Male', name='Hubert Oliveras', course='OOP', roll=351719, marks=63, email='Lawanda Wohlwend_Abram Nagao@MVC.com'),
 Row(age=28, gender='Male', name='Sebrina Maresca', course='PF', roll=361316, marks=62, email='Nicole Harwood_Latia Vanhoose@DB.com'),
 Row(age=29, gender='Male', name='Jalisa Swenson', course='PF', roll=372873, marks=45, email='Ernest Rossbach_Toshiko Hillyard@DB.com'),
 Row(age=28, gender='Male', name='Kizzy Brenner', course='DB', roll=381712, marks=36, email='Paris Hutton_Kena Wild@MVC.com'),
 Row(age=28, gender='Male', name='Toshiko Hillyard', course='DB', roll=392218, marks=47, email='Leontine Phillips_Billi Clore@MVC.com'),
 Row(age=28, gender='Male', name='Elenore Choy', course='PF', roll=422704, marks=66, email='Marylee Capasso_Nicole Harwood@MVC.com'),
 Row(age=28, gender='Male', name='Dustin Feagins', course='PF', roll=461839, marks=51, email='Neda Briski_Elenore Choy@Cloud.com'),
 Row(age=29, gender='Male', name='Annika Hoffman', course='OOP', roll=472550, marks=35, email='Mitzi Seldon_Abram Nagao@DSA.com'),
 Row(age=29, gender='Male', name='Paris Hutton', course='DB', roll=481229, marks=57, email='Clementina Menke_Paris Hutton@MVC.com'),
 Row(age=29, gender='Male', name='Billi Clore', course='Cloud', roll=512047, marks=76, email='Taryn Brownlee_Judie Chipps@DSA.com'),
 Row(age=29, gender='Male', name='Toshiko Hillyard', course='OOP', roll=521221, marks=77, email='Hubert Oliveras_Latia Vanhoose@MVC.com'),
 Row(age=28, gender='Male', name='Margene Moores', course='PF', roll=531530, marks=53, email='Cheri Kenney_Melani Engberg@OOP.com'),
 Row(age=29, gender='Male', name='Celeste Lollis', course='DSA', roll=562065, marks=85, email='Jc Andrepont_Melani Engberg@OOP.com'),
 Row(age=28, gender='Male', name='Marylee Capasso', course='OOP', roll=581756, marks=52, email='Jeannetta Golden_Loris Crossett@MVC.com'),
 Row(age=29, gender='Male', name='Maybell Duguay', course='DSA', roll=592061, marks=83, email='Eda Neathery_Jenna Montague@Cloud.com'),
 Row(age=28, gender='Male', name='Mitzi Seldon', course='DSA', roll=622981, marks=45, email='Lawanda Wohlwend_Loris Crossett@DSA.com'),
 Row(age=28, gender='Male', name='Priscila Tavernier', course='PF', roll=642594, marks=27, email='Marylee Capasso_Claude Panos@DSA.com'),
 Row(age=29, gender='Male', name='Tamera Blakley', course='MVC', roll=651649, marks=92, email='Latia Vanhoose_Toshiko Hillyard@MVC.com'),
 Row(age=28, gender='Male', name='Sheryll Towler', course='MVC', roll=661079, marks=89, email='Tijuana Kropf_Mickey Cortright@DB.com'),
 Row(age=29, gender='Male', name='Hubert Oliveras', course='MVC', roll=672451, marks=28, email='Annika Hoffman_Mickey Cortright@DSA.com'),
 Row(age=29, gender='Male', name='Sheryll Towler', course='PF', roll=682533, marks=42, email='Billi Clore_Anna Santos@PF.com'),
 Row(age=29, gender='Male', name='Maybell Duguay', course='PF', roll=701486, marks=99, email='Clementina Menke_Latia Vanhoose@Cloud.com'),
 Row(age=29, gender='Male', name='Jenna Montague', course='MVC', roll=711153, marks=45, email='Marylee Capasso_Hubert Oliveras@DB.com'),
 Row(age=28, gender='Male', name='Annika Hoffman', course='Cloud', roll=722193, marks=55, email='Taryn Brownlee_Elenore Choy@DB.com'),
 Row(age=29, gender='Male', name='Jeannetta Golden', course='MVC', roll=741875, marks=57, email='Sheryll Towler_Cheri Kenney@DSA.com'),
 Row(age=29, gender='Male', name='Paris Hutton', course='MVC', roll=752504, marks=22, email='Elenore Choy_Elenore Choy@DB.com'),
 Row(age=28, gender='Male', name='Alberta Freund', course='PF', roll=781061, marks=75, email='Leontine Phillips_Bonita Higuera@PF.com'),
 Row(age=28, gender='Male', name='Anna Santos', course='OOP', roll=822396, marks=47, email='Leontine Phillips_Gonzalo Ferebee@Cloud.com'),
 Row(age=28, gender='Male', name='Sheryll Towler', course='DSA', roll=831562, marks=59, email='Kena Wild_Gonzalo Ferebee@Cloud.com'),
 Row(age=29, gender='Male', name='Neda Briski', course='PF', roll=842515, marks=68, email='Neda Briski_Hubert Oliveras@OOP.com'),
 Row(age=29, gender='Male', name='Clementina Menke', course='DB', roll=882200, marks=76, email='Michelle Ruggiero_Jenna Montague@MVC.com'),
 Row(age=28, gender='Male', name='Margene Moores', course='DSA', roll=892010, marks=93, email='Anna Santos_Naoma Fritts@DSA.com'),
 Row(age=29, gender='Male', name='Loris Crossett', course='PF', roll=911593, marks=46, email='Gonzalo Ferebee_Mitzi Seldon@PF.com'),
 Row(age=29, gender='Male', name='Naoma Fritts', course='DB', roll=931295, marks=79, email='Hubert Oliveras_Sheryll Towler@DSA.com'),
 Row(age=29, gender='Male', name='Abram Nagao', course='MVC', roll=962235, marks=32, email='Jenna Montague_Gonzalo Ferebee@DSA.com'),
 Row(age=29, gender='Male', name='Niki Klimek', course='PF', roll=982443, marks=94, email='Santa Kerfien_Kizzy Brenner@DB.com'),
 Row(age=28, gender='Male', name='Jenna Montague', course='DSA', roll=1002103, marks=36, email='Melani Engberg_Hubert Oliveras@PF.com'),
 Row(age=29, gender='Male', name='Michelle Ruggiero', course='DSA', roll=1022971, marks=99, email='Cordie Harnois_Clementina Menke@OOP.com'),
 Row(age=28, gender='Male', name='Annika Hoffman', course='DB', roll=1031544, marks=44, email='Dustin Feagins_Somer Stoecker@DB.com'),
 Row(age=28, gender='Male', name='Billi Clore', course='MVC', roll=1052566, marks=78, email='Naoma Fritts_Margene Moores@DSA.com'),
 Row(age=29, gender='Male', name='Clementina Menke', course='PF', roll=1071717, marks=54, email='Celeste Lollis_Leontine Phillips@OOP.com'),
 Row(age=29, gender='Male', name='Donna Yerby', course='DSA', roll=1092702, marks=79, email='Marylee Capasso_Alberta Freund@OOP.com'),
 Row(age=29, gender='Male', name='Abram Nagao', course='PF', roll=1112161, marks=42, email='Nicole Harwood_Niki Klimek@DB.com'),
 Row(age=29, gender='Male', name='Nicole Harwood', course='Cloud', roll=1152571, marks=62, email='Latia Vanhoose_Maybell Duguay@PF.com'),
 Row(age=28, gender='Male', name='Jalisa Swenson', course='PF', roll=1192555, marks=77, email='Marylee Capasso_Celeste Lollis@Cloud.com'),
 Row(age=28, gender='Male', name='Nicole Harwood', course='DB', roll=1211495, marks=28, email='Melani Engberg_Jc Andrepont@Cloud.com'),
 Row(age=28, gender='Male', name='Nicole Harwood', course='OOP', roll=1242426, marks=71, email='Billi Clore_Loris Crossett@Cloud.com'),
 Row(age=28, gender='Male', name='Gonzalo Ferebee', course='Cloud', roll=1251176, marks=60, email='Santa Kerfien_Tamera Blakley@PF.com'),
 Row(age=29, gender='Male', name='Jalisa Swenson', course='Cloud', roll=1261533, marks=70, email='Dustin Feagins_Nicole Harwood@PF.com'),
 Row(age=28, gender='Male', name='Paris Hutton', course='MVC', roll=1292279, marks=26, email='Paris Hutton_Eda Neathery@DSA.com'),
 Row(age=28, gender='Male', name='Bonita Higuera', course='Cloud', roll=1312294, marks=94, email='Eda Neathery_Priscila Tavernier@PF.com'),
 Row(age=29, gender='Male', name='Jalisa Swenson', course='PF', roll=1332072, marks=88, email='Billi Clore_Kizzy Brenner@Cloud.com'),
 Row(age=28, gender='Male', name='Clementina Menke', course='OOP', roll=1341574, marks=46, email='Elenore Choy_Mickey Cortright@DB.com'),
 Row(age=28, gender='Male', name='Gonzalo Ferebee', course='PF', roll=1352348, marks=95, email='Neda Briski_Somer Stoecker@DB.com'),
 Row(age=28, gender='Male', name='Lawanda Wohlwend', course='PF', roll=1372552, marks=88, email='Hubert Oliveras_Tijuana Kropf@DSA.com'),
 Row(age=28, gender='Male', name='Abram Nagao', course='DSA', roll=1382959, marks=66, email='Michelle Ruggiero_Kena Wild@OOP.com'),
 Row(age=28, gender='Male', name='Bonita Higuera', course='Cloud', roll=1401526, marks=24, email='Jc Andrepont_Cheri Kenney@Cloud.com'),
 Row(age=29, gender='Male', name='Niki Klimek', course='MVC', roll=1472917, marks=36, email='Sebrina Maresca_Sheryll Towler@MVC.com'),
 Row(age=28, gender='Male', name='Jc Andrepont', course='DSA', roll=1492828, marks=78, email='Celeste Lollis_Kizzy Brenner@MVC.com'),
 Row(age=28, gender='Male', name='Hubert Oliveras', course='PF', roll=1521724, marks=91, email='Eda Neathery_Jeannetta Golden@MVC.com'),
 Row(age=28, gender='Male', name='Paris Hutton', course='MVC', roll=1602777, marks=53, email='Sheryll Towler_Loris Crossett@DSA.com'),
 Row(age=28, gender='Male', name='Marylee Capasso', course='DB', roll=1611411, marks=96, email='Annika Hoffman_Loris Crossett@PF.com'),
 Row(age=28, gender='Male', name='Anna Santos', course='OOP', roll=1621905, marks=24, email='Elenore Choy_Santa Kerfien@DB.com'),
 Row(age=28, gender='Male', name='Neda Briski', course='DSA', roll=1632185, marks=93, email='Clementina Menke_Toshiko Hillyard@Cloud.com'),
 Row(age=29, gender='Male', name='Alberta Freund', course='DB', roll=1671638, marks=98, email='Clementina Menke_Jalisa Swenson@Cloud.com'),
 Row(age=28, gender='Male', name='Celeste Lollis', course='DB', roll=1692106, marks=36, email='Neda Briski_Abram Nagao@MVC.com'),
 Row(age=29, gender='Male', name='Nicole Harwood', course='MVC', roll=1761454, marks=34, email='Taryn Brownlee_Billi Clore@DSA.com'),
 Row(age=29, gender='Male', name='Claude Panos', course='DSA', roll=1771605, marks=50, email='Claude Panos_Tamera Blakley@OOP.com'),
 Row(age=29, gender='Male', name='Dustin Feagins', course='DB', roll=1782045, marks=81, email='Cordie Harnois_Toshiko Hillyard@OOP.com'),
 Row(age=29, gender='Male', name='Toshiko Hillyard', course='DSA', roll=1791364, marks=50, email='Jc Andrepont_Nicole Harwood@MVC.com'),
 Row(age=28, gender='Male', name='Alberta Freund', course='Cloud', roll=1802934, marks=24, email='Maybell Duguay_Paris Hutton@PF.com'),
 Row(age=29, gender='Male', name='Latia Vanhoose', course='Cloud', roll=1832268, marks=60, email='Marylee Capasso_Santa Kerfien@MVC.com'),
 Row(age=29, gender='Male', name='Alberta Freund', course='OOP', roll=1841931, marks=37, email='Jenna Montague_Taryn Brownlee@Cloud.com'),
 Row(age=29, gender='Male', name='Celeste Lollis', course='PF', roll=1861656, marks=67, email='Niki Klimek_Lawanda Wohlwend@DB.com'),
 Row(age=29, gender='Male', name='Tijuana Kropf', course='DB', roll=1882795, marks=92, email='Hubert Oliveras_Elenore Choy@Cloud.com'),
 Row(age=28, gender='Male', name='Somer Stoecker', course='Cloud', roll=1891261, marks=30, email='Taryn Brownlee_Sheryll Towler@PF.com'),
 Row(age=28, gender='Male', name='Ernest Rossbach', course='DB', roll=1901492, marks=54, email='Latia Vanhoose_Jc Andrepont@MVC.com'),
 Row(age=29, gender='Male', name='Sebrina Maresca', course='PF', roll=1932455, marks=23, email='Tijuana Kropf_Naoma Fritts@Cloud.com'),
 Row(age=29, gender='Male', name='Marylee Capasso', course='DSA', roll=1942185, marks=37, email='Tijuana Kropf_Latia Vanhoose@DSA.com'),
 Row(age=29, gender='Male', name='Jeannetta Golden', course='Cloud', roll=1952763, marks=67, email='Jenna Montague_Jeannetta Golden@OOP.com'),
 Row(age=29, gender='Male', name='Niki Klimek', course='MVC', roll=1962371, marks=78, email='Marylee Capasso_Mickey Cortright@PF.com'),
 Row(age=29, gender='Male', name='Tamera Blakley', course='OOP', roll=1981124, marks=46, email='Taryn Brownlee_Eda Neathery@DB.com'),
 Row(age=28, gender='Male', name='Santa Kerfien', course='MVC', roll=1992202, marks=23, email='Annika Hoffman_Tamera Blakley@OOP.com'),
 Row(age=29, gender='Male', name='Somer Stoecker', course='OOP', roll=2011301, marks=47, email='Somer Stoecker_Anna Santos@MVC.com'),
 Row(age=28, gender='Male', name='Billi Clore', course='PF', roll=2022282, marks=77, email='Anna Santos_Claude Panos@Cloud.com'),
 Row(age=28, gender='Male', name='Kena Wild', course='DB', roll=2031530, marks=93, email='Jc Andrepont_Jc Andrepont@PF.com'),
 Row(age=28, gender='Male', name='Marylee Capasso', course='DSA', roll=2081560, marks=20, email='Sheryll Towler_Donna Yerby@Cloud.com'),
 Row(age=28, gender='Male', name='Neda Briski', course='Cloud', roll=2092176, marks=81, email='Celeste Lollis_Maybell Duguay@PF.com'),
 Row(age=29, gender='Male', name='Donna Yerby', course='DSA', roll=2102495, marks=97, email='Paris Hutton_Celeste Lollis@PF.com'),
 Row(age=29, gender='Male', name='Judie Chipps', course='DB', roll=2112234, marks=94, email='Dustin Feagins_Tamera Blakley@PF.com'),
 Row(age=29, gender='Male', name='Jeannetta Golden', course='MVC', roll=2132781, marks=93, email='Kizzy Brenner_Cheri Kenney@MVC.com'),
 Row(age=29, gender='Male', name='Naoma Fritts', course='PF', roll=2141246, marks=91, email='Mitzi Seldon_Cordie Harnois@Cloud.com'),
 Row(age=29, gender='Male', name='Somer Stoecker', course='MVC', roll=2151024, marks=36, email='Loris Crossett_Tamera Blakley@DB.com'),
 Row(age=28, gender='Male', name='Toshiko Hillyard', course='PF', roll=2162776, marks=54, email='Jenna Montague_Niki Klimek@MVC.com'),
 Row(age=28, gender='Male', name='Jeannetta Golden', course='DB', roll=2171387, marks=76, email='Cheri Kenney_Billi Clore@DB.com'),
 Row(age=29, gender='Male', name='Mitzi Seldon', course='Cloud', roll=2202649, marks=43, email='Santa Kerfien_Loris Crossett@Cloud.com'),
 Row(age=28, gender='Male', name='Jalisa Swenson', course='DSA', roll=2222704, marks=91, email='Judie Chipps_Jalisa Swenson@Cloud.com'),
 Row(age=28, gender='Male', name='Priscila Tavernier', course='OOP', roll=2232863, marks=60, email='Bonita Higuera_Lawanda Wohlwend@MVC.com'),
 Row(age=29, gender='Male', name='Margene Moores', course='Cloud', roll=2241434, marks=71, email='Mitzi Seldon_Michelle Ruggiero@Cloud.com'),
 Row(age=29, gender='Male', name='Annika Hoffman', course='PF', roll=2301940, marks=81, email='Jenna Montague_Sheryll Towler@Cloud.com'),
 Row(age=28, gender='Male', name='Kizzy Brenner', course='DB', roll=2322537, marks=56, email='Jenna Montague_Latia Vanhoose@MVC.com'),
 Row(age=29, gender='Male', name='Michelle Ruggiero', course='Cloud', roll=2332207, marks=72, email='Gonzalo Ferebee_Melani Engberg@OOP.com'),
 Row(age=29, gender='Male', name='Alberta Freund', course='DSA', roll=2341989, marks=68, email='Jeannetta Golden_Priscila Tavernier@PF.com'),
 Row(age=29, gender='Male', name='Mickey Cortright', course='OOP', roll=2361202, marks=59, email='Kizzy Brenner_Eda Neathery@MVC.com'),
 Row(age=29, gender='Male', name='Latia Vanhoose', course='OOP', roll=2372748, marks=94, email='Latia Vanhoose_Latia Vanhoose@OOP.com'),
 Row(age=29, gender='Male', name='Naoma Fritts', course='OOP', roll=2382829, marks=37, email='Ernest Rossbach_Celeste Lollis@PF.com'),
 Row(age=28, gender='Male', name='Melani Engberg', course='MVC', roll=2412019, marks=54, email='Latia Vanhoose_Melani Engberg@DSA.com'),
 Row(age=28, gender='Male', name='Sebrina Maresca', course='Cloud', roll=2452108, marks=41, email='Billi Clore_Loris Crossett@DSA.com'),
 Row(age=28, gender='Male', name='Judie Chipps', course='DB', roll=2461986, marks=53, email='Niki Klimek_Judie Chipps@MVC.com'),
 Row(age=29, gender='Male', name='Jenna Montague', course='DSA', roll=2472773, marks=81, email='Margene Moores_Bonita Higuera@DSA.com'),
 Row(age=29, gender='Male', name='Cheri Kenney', course='Cloud', roll=2491705, marks=64, email='Toshiko Hillyard_Mickey Cortright@PF.com'),
 Row(age=28, gender='Male', name='Priscila Tavernier', course='Cloud', roll=2552194, marks=42, email='Jeannetta Golden_Abram Nagao@PF.com'),
 Row(age=28, gender='Male', name='Claude Panos', course='OOP', roll=2562357, marks=50, email='Naoma Fritts_Anna Santos@Cloud.com'),
 Row(age=28, gender='Male', name='Gonzalo Ferebee', course='MVC', roll=2572197, marks=43, email='Marylee Capasso_Jc Andrepont@DB.com'),
 Row(age=29, gender='Male', name='Nicole Harwood', course='Cloud', roll=2581369, marks=26, email='Paris Hutton_Alberta Freund@MVC.com'),
 Row(age=28, gender='Male', name='Paris Hutton', course='OOP', roll=2592369, marks=60, email='Taryn Brownlee_Sheryll Towler@OOP.com'),
 Row(age=28, gender='Male', name='Sheryll Towler', course='DSA', roll=2612360, marks=27, email='Celeste Lollis_Paris Hutton@OOP.com'),
 Row(age=28, gender='Male', name='Mitzi Seldon', course='DB', roll=2622118, marks=55, email='Mickey Cortright_Mitzi Seldon@MVC.com'),
 Row(age=28, gender='Male', name='Billi Clore', course='PF', roll=2642909, marks=58, email='Loris Crossett_Sebrina Maresca@OOP.com'),
 Row(age=28, gender='Male', name='Abram Nagao', course='Cloud', roll=2652463, marks=21, email='Eda Neathery_Annika Hoffman@Cloud.com'),
 Row(age=29, gender='Male', name='Tamera Blakley', course='DSA', roll=2661934, marks=23, email='Alberta Freund_Tijuana Kropf@Cloud.com'),
 Row(age=28, gender='Male', name='Mitzi Seldon', course='PF', roll=2701239, marks=76, email='Alberta Freund_Cordie Harnois@Cloud.com'),
 Row(age=29, gender='Male', name='Sebrina Maresca', course='PF', roll=2712040, marks=23, email='Jeannetta Golden_Judie Chipps@DB.com'),
 Row(age=29, gender='Male', name='Somer Stoecker', course='PF', roll=2721652, marks=36, email='Tijuana Kropf_Michelle Ruggiero@Cloud.com'),
 Row(age=28, gender='Male', name='Santa Kerfien', course='DB', roll=2732421, marks=79, email='Claude Panos_Alberta Freund@DB.com'),
 Row(age=28, gender='Male', name='Clementina Menke', course='DSA', roll=2772189, marks=98, email='Donna Yerby_Judie Chipps@PF.com'),
 Row(age=29, gender='Male', name='Tijuana Kropf', course='Cloud', roll=2781801, marks=68, email='Alberta Freund_Cordie Harnois@Cloud.com'),
 Row(age=29, gender='Male', name='Leontine Phillips', course='PF', roll=2832158, marks=26, email='Margene Moores_Claude Panos@MVC.com'),
 Row(age=29, gender='Male', name='Abram Nagao', course='DB', roll=2841061, marks=25, email='Leontine Phillips_Toshiko Hillyard@Cloud.com'),
 Row(age=28, gender='Male', name='Loris Crossett', course='OOP', roll=2852490, marks=25, email='Loris Crossett_Donna Yerby@DSA.com'),
 Row(age=28, gender='Male', name='Michelle Ruggiero', course='DB', roll=2891164, marks=60, email='Gonzalo Ferebee_Priscila Tavernier@DSA.com'),
 Row(age=29, gender='Male', name='Niki Klimek', course='DB', roll=2912538, marks=67, email='Jc Andrepont_Mitzi Seldon@DSA.com'),
 Row(age=28, gender='Male', name='Gonzalo Ferebee', course='Cloud', roll=2922041, marks=38, email='Clementina Menke_Taryn Brownlee@OOP.com'),
 Row(age=29, gender='Male', name='Melani Engberg', course='DB', roll=2941257, marks=98, email='Claude Panos_Kena Wild@DB.com'),
 Row(age=29, gender='Male', name='Billi Clore', course='DSA', roll=2952091, marks=52, email='Jenna Montague_Mickey Cortright@DB.com'),
 Row(age=29, gender='Male', name='Claude Panos', course='PF', roll=2961015, marks=33, email='Elenore Choy_Santa Kerfien@DSA.com'),

# Spark DF (Spark SQL)

In [0]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('DF to RDD').getOrCreate()
df = spark.read.options(header='True',inferschema='True').csv('/FileStore/tables/StudentData.csv')
df.show()

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

In [0]:
df.createOrReplaceTempView('Students') # it creats a temp view if not exists or it will replace the existing one with new one

In [0]:
spark.sql("SELECT * FROM Students WHERE course = 'DB'").show()

+---+------+-----------------+------+-------+-----+--------------------+
|age|gender|             name|course|   roll|marks|               email|
+---+------+-----------------+------+-------+-----+--------------------+
| 28|Female|  Hubert Oliveras|    DB|   2984|   59|Annika Hoffman_Na...|
| 29|Female|     Elenore Choy|    DB|  32877|   29|Billi Clore_Mitzi...|
| 29|  Male|  Ernest Rossbach|    DB| 111449|   53|Maybell Duguay_Ab...|
| 28|Female|   Latia Vanhoose|    DB| 122502|   27|Latia Vanhoose_Mi...|
| 29|Female|   Latia Vanhoose|    DB| 152159|   27|Claude Panos_Sant...|
| 28|Female| Mickey Cortright|    DB| 192537|   62|Ernest Rossbach_M...|
| 28|Female|      Anna Santos|    DB| 311589|   79|Celeste Lollis_Mi...|
| 28|  Male|    Kizzy Brenner|    DB| 381712|   36|Paris Hutton_Kena...|
| 28|  Male| Toshiko Hillyard|    DB| 392218|   47|Leontine Phillips...|
| 29|  Male|     Paris Hutton|    DB| 481229|   57|Clementina Menke_...|
| 28|Female| Mickey Cortright|    DB| 551389|   43|Tijuana Kropf_Jen...|
| 28|Female|Leontine Phillips|    DB| 602404|   48|Neda Briski_Cheri...|
| 28|Female|  Hubert Oliveras|    DB| 771081|   79|Kizzy Brenner_Dus...|
| 29|Female|     Elenore Choy|    DB| 811824|   55|Maybell Duguay_Me...|
| 29|  Male| Clementina Menke|    DB| 882200|   76|Michelle Ruggiero...|
| 29|Female|  Sebrina Maresca|    DB| 922210|   54|Toshiko Hillyard_...|
| 29|  Male|     Naoma Fritts|    DB| 931295|   79|Hubert Oliveras_S...|
| 28|  Male|   Annika Hoffman|    DB|1031544|   44|Dustin Feagins_So...|
| 28|  Male|   Nicole Harwood|    DB|1211495|   28|Melani Engberg_Jc...|
| 29|Female|     Claude Panos|    DB|1222887|   75|Hubert Oliveras_S...|
+---+------+-----------------+------+-------+-----+--------------------+
only showing top 20 rows

In [0]:
spark.sql("SELECT course, gender, COUNT('*') AS count, SUM(marks) AS total_marks FROM Students GROUP BY course, gender").show()

+------+------+-----+-----------+
|course|gender|count|total_marks|
+------+------+-----+-----------+
|   OOP|  Male|   70|       4234|
|    DB|  Male|   82|       5073|
| Cloud|Female|  106|       6316|
|   MVC|  Male|   86|       5241|
|   DSA|Female|   98|       6124|
|    PF|  Male|   97|       5960|
|   MVC|Female|   71|       4344|
| Cloud|  Male|   86|       5127|
|    PF|Female|   69|       3973|
|   DSA|  Male|   78|       4826|
|    DB|Female|   75|       4197|
|   OOP|Female|   82|       4682|
+------+------+-----+-----------+

# Spark DF (Write DF)

In [0]:
df.show()

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

In [0]:
df.rdd.getNumPartitions() # to check the no of partitions in DF

Out[61]: 1

In [0]:
# ther are several modes to perform write actions(append, overwrite, ignore, error)
df.write.options(header='True').csv('/FileStore/tables/StudentData/output')

---------------------------------------------------------------------------
AnalysisException                         Traceback (most recent call last)
<command-3525593887850576> in <module>
      1 # ther are several modes to perform write or read or .. actions(write, append, overwrite, ignore, error)
----> 2 df.write.options(header='True').csv('/FileStore/tables/StudentData/output')

/databricks/spark/python/pyspark/sql/readwriter.py in csv(self, path, mode, compression, sep, quote, escape, header, nullValue, escapeQuotes, quoteAll, dateFormat, timestampFormat, ignoreLeadingWhiteSpace, ignoreTrailingWhiteSpace, charToEscapeQuoteEscaping, encoding, emptyValue, lineSep)
    953                        charToEscapeQuoteEscaping=charToEscapeQuoteEscaping,
    954                        encoding=encoding, emptyValue=emptyValue, lineSep=lineSep)
--> 955         self._jwrite.csv(path)
    956
    957     def orc(self, path, mode=None, partitionBy=None, compression=None):

/databricks/spark/python/lib/py4j-0.10.9.1-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1302
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    121                 # Hide where the exception came from that shows a non-Pythonic
    122                 # JVM exception message.
--> 123                 raise converted from None
    124             else:
    125                 raise

AnalysisException: path dbfs:/FileStore/tables/StudentData/output already exists.

In [0]:
df.write.mode('overwrite').options(header='True').csv('/FileStore/tables/StudentData/output')

In [0]:
# reading the above created df
spark.read.options(header='True', inferschema='True').csv('/FileStore/tables/StudentData/output').show()

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

In [0]:
df = df.groupBy(df.course, df.gender).agg(count('*').alias('total_count'))
df.show()

+------+------+-----------+
|course|gender|total_count|
+------+------+-----------+
|   OOP|  Male|         70|
|    DB|  Male|         82|
| Cloud|Female|        106|
|   MVC|  Male|         86|
|   DSA|Female|         98|
|    PF|  Male|         97|
|   MVC|Female|         71|
| Cloud|  Male|         86|
|    PF|Female|         69|
|   DSA|  Male|         78|
|    DB|Female|         75|
|   OOP|Female|         82|
+------+------+-----------+

In [0]:
# overwriting the groupBy DF in existing DF
df.write.mode('overwrite').options(header='True').csv('/FileStore/tables/StudentData/output')

In [0]:
# reading the overwritten DF
df = spark.read.options(header='True', inferschema='True').csv('/FileStore/tables/StudentData/output')
df.show()

+------+------+-----------+
|course|gender|total_count|
+------+------+-----------+
|   OOP|  Male|         70|
|    DB|  Male|         82|
| Cloud|Female|        106|
|   MVC|  Male|         86|
|   DSA|Female|         98|
|    PF|  Male|         97|
|   MVC|Female|         71|
| Cloud|  Male|         86|
|    PF|Female|         69|
|   DSA|  Male|         78|
|    DB|Female|         75|
|   OOP|Female|         82|
+------+------+-----------+

# Mini Project

In [0]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import min, max, count, avg, mean, sum, col, lit, udf
from pyspark.sql.types import StructType, StructField, IntegerType, StringType, DoubleType

In [0]:
spark = SparkSession.builder.appName('Mini Project').getOrCreate()
df = spark.read.options(header='True', inferschema='True').csv('/FileStore/tables/OfficeDataProject.csv')
df.show()

+-----------+-------------------+----------+-----+------+---+-----+
|employee_id|      employee_name|department|state|salary|age|bonus|
+-----------+-------------------+----------+-----+------+---+-----+
|       1000|          Nitz Leif| Marketing|   CA|  6131| 26|  543|
|       1001|    Melissia Dedman|   Finance|   AK|  4027| 43| 1290|
|       1002|  Rudolph Barringer|        HR|   LA|  3122| 43| 1445|
|       1003|        Tamra Amber|  Accounts|   AK|  5717| 47| 1291|
|       1004|        Mullan Nitz|Purchasing|   CA|  5685| 34| 1394|
|       1005|      Zollner Karie|  Accounts|   CA|  2843| 27| 1078|
|       1006|Kaczorowski Zollner|     Sales|   CA|  7201| 21| 1834|
|       1007|      Nakano Locust| Marketing|   LA|  3444| 23| 1823|
|       1008|  Recalde Kensinger|  Accounts|   LA|  3704| 48| 1330|
|       1009|        Imai Hallie|  Accounts|   AK|  5061| 38| 1557|
|       1010|    Debroah Gallman|  Accounts|   NY|  9308| 35|  817|
|       1011|   Barringer Escoto|Purchasing|   WA|  1685| 49| 1706|
|       1012|      Soules Coogan|  Accounts|   AK|  8330| 43| 1914|
|       1013|      Luisa Suzanne|  Accounts|   CA|  1151| 37| 1095|
|       1014|      Marvis Cobian|Purchasing|   NY|  5061| 41| 1765|
|       1015|   Cobian Kensinger|     Sales|   LA|  1983| 21|  632|
|       1016|      Gilma Margret| Marketing|   CA|  2919| 45| 1762|
|       1017| Ellingsworth Ilana|  Accounts|   WA|  9614| 26| 1964|
|       1018| Vankirk Jacquelyne|Purchasing|   NY|  8636| 47| 1192|
|       1019|    Zollner Juliana|        HR|   NY|  9739| 30| 1119|
+-----------+-------------------+----------+-----+------+---+-----+
only showing top 20 rows

In [0]:
countDF = df
print('Total number of employees are: ', countDF.count())

Total number of employees are:  1000

In [0]:
depCountDF = df

# method 1
depCountDF = depCountDF.groupBy(depCountDF.department).agg(count('*').alias('department_count')).count()
print('Total number of departments in the company are: ', depCountDF)

# method 2
df.select('department').dropDuplicates(['department']).count()

Total number of departments in the company are:  6
Out[133]: 6

In [0]:
depNameDF = df

#method 1
depNameDF.groupBy(depNameDF.department).agg(count('*')).select(df.department).show()

#method 2
df.select('department').dropDuplicates(['department']).show()

+----------+
|department|
+----------+
|     Sales|
|        HR|
|   Finance|
|Purchasing|
| Marketing|
|  Accounts|
+----------+

+----------+
|department|
+----------+
|     Sales|
|        HR|
|   Finance|
|Purchasing|
| Marketing|
|  Accounts|
+----------+

In [0]:
empCountInDepDF = df

empCountInDepDF.groupBy(df.department).agg(count('*').alias('total_employees')).show()

+----------+---------------+
|department|total_employees|
+----------+---------------+
|     Sales|            169|
|        HR|            171|
|   Finance|            162|
|Purchasing|            166|
| Marketing|            170|
|  Accounts|            162|
+----------+---------------+

In [0]:
empCountInStateDF = df

empCountInStateDF.groupBy(df.state).agg(count('*').alias('total_employees_state')).show()

+-----+---------------------+
|state|total_employees_state|
+-----+---------------------+
|   LA|                  205|
|   CA|                  205|
|   WA|                  208|
|   NY|                  173|
|   AK|                  209|
+-----+---------------------+

In [0]:
df.groupBy(df.state, df.department).agg(count('*').alias('total_emp_state_dep')).show()

+-----+----------+-------------------+
|state|department|total_emp_state_dep|
+-----+----------+-------------------+
|   CA|     Sales|                 42|
|   CA| Marketing|                 33|
|   NY|  Accounts|                 34|
|   NY|     Sales|                 27|
|   CA|   Finance|                 35|
|   CA|  Accounts|                 35|
|   CA|Purchasing|                 32|
|   WA|        HR|                 47|
|   AK|Purchasing|                 30|
|   WA|  Accounts|                 27|
|   WA|Purchasing|                 38|
|   AK|     Sales|                 38|
|   AK|  Accounts|                 37|
|   WA| Marketing|                 39|
|   LA|        HR|                 41|
|   LA|     Sales|                 35|
|   AK|        HR|                 25|
|   LA|   Finance|                 29|
|   AK|   Finance|                 37|
|   LA|Purchasing|                 45|
+-----+----------+-------------------+
only showing top 20 rows

In [0]:
minMaxDF = df

minMaxDF = minMaxDF.groupBy(df.department).agg(min(df.salary).alias('min_sal'), max(df.salary).alias('max_sal')).sort(col('min_sal').asc(), col('max_sal').asc())
minMaxDF.show()

+----------+-------+-------+
|department|min_sal|max_sal|
+----------+-------+-------+
|   Finance|   1006|   9899|
|  Accounts|   1007|   9890|
|        HR|   1013|   9982|
| Marketing|   1031|   9974|
|     Sales|   1103|   9982|
|Purchasing|   1105|   9985|
+----------+-------+-------+

In [0]:
noEmp = df

noEmp1 = noEmp.filter(df.state == 'NY').groupBy(df.state).agg(avg('bonus').alias('avg_bonus')).select(col('avg_bonus')).collect()
#collect will provide us with the actual data, it will simply eleminate the abstraction layer of DF and provid us the actual data for the RDD
print(noEmp1)
print(noEmp1[0]['avg_bonus'])

avgBonus = noEmp.filter(df.state == 'NY').groupBy(df.state).agg(avg('bonus').alias('avg_bonus')).select(col('avg_bonus')).collect()[0]['avg_bonus']
print(avgBonus, type(avgBonus))

noEmp = noEmp.filter((noEmp.state == 'NY') & (noEmp.department == 'Finance') & (df.bonus > avgBonus))
print('**********************')
print('No of employees workint in NY and in Finance dep whose bonuse is grater than avg bonus of emp in NY are: ', noEmp.count())
noEmp.show()

[Row(avg_bonus=1251.3468208092486)]
1251.3468208092486
1251.3468208092486 <class 'float'>
**********************
No of employees workint in NY and in Finance dep whose bonuse is grater than avg bonus of emp in NY are:  17
+-----------+--------------------+----------+-----+------+---+-----+
|employee_id|       employee_name|department|state|salary|age|bonus|
+-----------+--------------------+----------+-----+------+---+-----+
|       1035|       Vivan Sifford|   Finance|   NY|  1129| 35| 1261|
|       1073|      Herder Gallman|   Finance|   NY|  1988| 31| 1402|
|       1082|          Nena Rocha|   Finance|   NY|  3417| 25| 1647|
|       1087|       Leif Lemaster|   Finance|   NY|  8642| 45| 1782|
|       1100|Ellingsworth Meli...|   Finance|   NY|  7845| 32| 1358|
|       1127|        Escoto Gilma|   Finance|   NY|  3426| 41| 1285|
|       1161|     Georgeanna Laub|   Finance|   NY|  2469| 26| 1679|
|       1175|     Durio Tenenbaum|   Finance|   NY|  2253| 42| 1684|
|       1180|       Juliana Grigg|   Finance|   NY|  8178| 42| 1617|
|       1215|        Tiffani Benz|   Finance|   NY|  1665| 41| 1969|
|       1220|          Nitz Ilana|   Finance|   NY|  2443| 50| 1342|
|       1342|   Phylicia Antonina|   Finance|   NY|  8626| 30| 1857|
|       1414|         Durio Janey|   Finance|   NY|  2992| 46| 1733|
|       1660|       Melissia Jere|   Finance|   NY|  9201| 21| 1533|
|       1737|      Yukiko Kreamer|   Finance|   NY|  7396| 20| 1332|
|       1738|      Nena Kensinger|   Finance|   NY|  8534| 41| 1610|
|       1815|      Antonina Ilana|   Finance|   NY|  2944| 28| 1718|
+-----------+--------------------+----------+-----+------+---+-----+

In [0]:
salRaisDF = df

def rais(age, salary):
    if age > 45:
        return salary + 500
    else:
        return salary

raisUDF = udf(lambda x, y: rais(x, y), IntegerType())
salRaisDF = salRaisDF.withColumn('salary', raisUDF(salRaisDF.age, salRaisDF.salary))
salRaisDF.show()

+-----------+-------------------+----------+-----+------+---+-----+
|employee_id|      employee_name|department|state|salary|age|bonus|
+-----------+-------------------+----------+-----+------+---+-----+
|       1000|          Nitz Leif| Marketing|   CA|  6131| 26|  543|
|       1001|    Melissia Dedman|   Finance|   AK|  4027| 43| 1290|
|       1002|  Rudolph Barringer|        HR|   LA|  3122| 43| 1445|
|       1003|        Tamra Amber|  Accounts|   AK|  6217| 47| 1291|
|       1004|        Mullan Nitz|Purchasing|   CA|  5685| 34| 1394|
|       1005|      Zollner Karie|  Accounts|   CA|  2843| 27| 1078|
|       1006|Kaczorowski Zollner|     Sales|   CA|  7201| 21| 1834|
|       1007|      Nakano Locust| Marketing|   LA|  3444| 23| 1823|
|       1008|  Recalde Kensinger|  Accounts|   LA|  4204| 48| 1330|
|       1009|        Imai Hallie|  Accounts|   AK|  5061| 38| 1557|
|       1010|    Debroah Gallman|  Accounts|   NY|  9308| 35|  817|
|       1011|   Barringer Escoto|Purchasing|   WA|  2185| 49| 1706|
|       1012|      Soules Coogan|  Accounts|   AK|  8330| 43| 1914|
|       1013|      Luisa Suzanne|  Accounts|   CA|  1151| 37| 1095|
|       1014|      Marvis Cobian|Purchasing|   NY|  5061| 41| 1765|
|       1015|   Cobian Kensinger|     Sales|   LA|  1983| 21|  632|
|       1016|      Gilma Margret| Marketing|   CA|  2919| 45| 1762|
|       1017| Ellingsworth Ilana|  Accounts|   WA|  9614| 26| 1964|
|       1018| Vankirk Jacquelyne|Purchasing|   NY|  9136| 47| 1192|
|       1019|    Zollner Juliana|        HR|   NY|  9739| 30| 1119|
+-----------+-------------------+----------+-----+------+---+-----+
only showing top 20 rows

In [0]:
# verification
salRaisDF.filter(salRaisDF.age > 45).show()
df.filter(df.age > 45).show()

+-----------+------------------+----------+-----+------+---+-----+
|employee_id|     employee_name|department|state|salary|age|bonus|
+-----------+------------------+----------+-----+------+---+-----+
|       1003|       Tamra Amber|  Accounts|   AK|  6217| 47| 1291|
|       1008| Recalde Kensinger|  Accounts|   LA|  4204| 48| 1330|
|       1011|  Barringer Escoto|Purchasing|   WA|  2185| 49| 1706|
|       1018|Vankirk Jacquelyne|Purchasing|   NY|  9136| 47| 1192|
|       1025|   Dionne Lemaster|     Sales|   AK|  5634| 48| 1356|
|       1030|        Trena Benz|  Accounts|   NY|  4876| 49| 1624|
|       1039|      Dynes Katlyn|  Accounts|   AK|  3539| 48|  834|
|       1058|      Clune Norene|   Finance|   AK|  2105| 49|  801|
|       1074|      Rocha Dionne|  Accounts|   CA|  3970| 49|  706|
|       1088|       Imai Locust|     Sales|   NY| 10482| 49| 1809|
|       1090| Clemencia Rudolph|   Finance|   NY|  1796| 50| 1209|
|       1099|    Zollner Marvis|Purchasing|   CA|  4730| 50|  951|
|       1118|     Kohn Antonina|     Sales|   CA|  9811| 48| 1229|
|       1126|     Norene Mayeda|  Accounts|   LA|  3600| 50| 1333|
|       1136|      Jaclyn Baros|     Sales|   LA|  2199| 48| 1094|
|       1164|    Gallman Nakano|     Sales|   CA|  7313| 47|  857|
|       1165|       Luisa Grigg|Purchasing|   AK|  9797| 48| 1545|
|       1169|   Kreamer Shandra|        HR|   WA|  5468| 46|  889|
|       1170|     Fender Coogan| Marketing|   AK|  1651| 50| 1845|
|       1183|  Lonergan Bergren|        HR|   NY|  8675| 46| 1730|
+-----------+------------------+----------+-----+------+---+-----+
only showing top 20 rows

+-----------+------------------+----------+-----+------+---+-----+
|employee_id|     employee_name|department|state|salary|age|bonus|
+-----------+------------------+----------+-----+------+---+-----+
|       1003|       Tamra Amber|  Accounts|   AK|  5717| 47| 1291|
|       1008| Recalde Kensinger|  Accounts|   LA|  3704| 48| 1330|
|       1011|  Barringer Escoto|Purchasing|   WA|  1685| 49| 1706|
|       1018|Vankirk Jacquelyne|Purchasing|   NY|  8636| 47| 1192|
|       1025|   Dionne Lemaster|     Sales|   AK|  5134| 48| 1356|
|       1030|        Trena Benz|  Accounts|   NY|  4376| 49| 1624|
|       1039|      Dynes Katlyn|  Accounts|   AK|  3039| 48|  834|
|       1058|      Clune Norene|   Finance|   AK|  1605| 49|  801|
|       1074|      Rocha Dionne|  Accounts|   CA|  3470| 49|  706|
|       1088|       Imai Locust|     Sales|   NY|  9982| 49| 1809|
|       1090| Clemencia Rudolph|   Finance|   NY|  1296| 50| 1209|
|       1099|    Zollner Marvis|Purchasing|   CA|  4230| 50|  951|
|       1118|     Kohn Antonina|     Sales|   CA|  9311| 48| 1229|
|       1126|     Norene Mayeda|  Accounts|   LA|  3100| 50| 1333|
|       1136|      Jaclyn Baros|     Sales|   LA|  1699| 48| 1094|
|       1164|    Gallman Nakano|     Sales|   CA|  6813| 47|  857|
|       1165|       Luisa Grigg|Purchasing|   AK|  9297| 48| 1545|
|       1169|   Kreamer Shandra|        HR|   WA|  4968| 46|  889|
|       1170|     Fender Coogan| Marketing|   AK|  1151| 50| 1845|
|       1183|  Lonergan Bergren|        HR|   NY|  8175| 46| 1730|
+-----------+------------------+----------+-----+------+---+-----+
only showing top 20 rows

In [0]:
filterEmpDF = df

#method 1
filterEmpDF = filterEmpDF.filter(filterEmpDF.age > 45)
print(filterEmpDF.count())

filterEmpDF.write.mode('overwrite').options(header='True').csv('/FileStore/tables/OfficeDataProject/output')

#method 2
df.filter(df.age > 45).write.mode('ignore').csv('/FileStore/tables/OfficeDataProject/output')

166

In [0]:
#verification

df1 = spark.read.options(header='True', inferdata='True').csv('/FileStore/tables/OfficeDataProject.csv')
df2 = spark.read.options(header='True', inferdata='True').csv('/FileStore/tables/OfficeDataProject/output')

print(df1.count())
print(df2.count())

1000
166